---
title: "The Road Not Taken: College Board Geomarkets and Recruiting Visits by Selective Colleges"
# author: ["Ozan Jaquette (UCLA)", "Karina Salazar (University of Arizona)", "Crystal Han (Stanford University)"]
bibliography: ./../../cb_geo/assets/bib/cb_geomarket_bib.bib
csl: ./../../cb_geo/assets/bib/chicago-author-date.csl
format:
  #docx:
  pdf:
    documentclass: article
    #papersize: letter
    number-sections: true
    number-depth: 2
    #toc: FALSE
    #pandoc_args: !expr rmdfiltr::add_wordcount_filter(rmdfiltr::add_citeproc_filter(args = NULL))
    #keep_tex: true
editor: visual
geometry:
  - margin=1in
fontsize: 11pt
header-includes:
  - \usepackage{setspace}
  - \doublespacing
---

```{r setup, include=FALSE}
library(knitr)
#library(bookdown)

# https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_pdf.pdf
library(kableExtra)

#hey ho This many words: {{< words-total >}}
```

\pagenumbering{roman}
\newpage

\pagenumbering{gobble}
\pagenumbering{arabic}

# Dependence and Patronage in the Enrollment Economy

<!--
Enrollment management (EM) is simultaneously a profession, an administrative structure, and an industry. The EM profession integrates techniques from marketing and economics in order to "influence the characteristics and the size of enrolled student bodies" [@RN2771, p. xiv]. As an administrative structure, offices of EM increasingly control and coordinate the functional activities of admissions, financial aid, and recruiting [@RN2406]. The enrollment management industry incorporates relevant actors in the organizational field, including colleges, professional associations (e.g., National Association for College Admission Counseling), and third-party servicers that supply products and consulting solutions to colleges (e.g., College Board, EAB).
-->

Resource dependence theory (RDT) [@RN959] describe power dynamics between actors in the higher education industry. RDT builds on Emerson's [@RN960] canonical definition of dependence: Actor $A$ depends on actor $B$ to the extent that $B$ controls goals that are valued by $A$ and cannot be fulfilled outside the $A-B$ relationship. @RN959 apply this concept to the organizational context. All organizations depend on resources from the external environment to survive and thrive. An external resource provider has power over a focal organization to the extent that (1) the resource is essential for organizational operations, (2) few alternative sources of the resource exist, and (3) the external organization has discretion over how the resource is allocated.

We place the concept dependence in dialogue Stevens and Gebre-Medhin's -@RN4517 discussion of patronage. @RN4517 define three institutional configurations -- associational, national service, and market -- that describe the evolution of US higher education. Early US colleges were "associational" in two ways. First, early colleges were voluntary "purpose-defined corporations" (p. 126) that relied on patronage from the religious congregations and businesses. The associational configuration has a second meaning -- consistent with RDT  -- the idea of colleges "knitting themselves together in a wide variety of interorganizational associations" [@RN4517, p. 126] to solve common problems. Examples include voluntary accreditation, professional associations, and member associations like the Consortium on Financing Financing Higher Education (COFHE). The national service configuration refers to the massive federal and state investment in higher education -- beginning around World War II -- as an engine of American political and technological development. Examples include federal research funding, state appropriations, and federal financial aid, which transformed US higher education into a national voucher system whereby federal funding follows students to their college of enrollment. The market configuration, although always present, is associated with contemporary state disinvestment in public higher education, coupled with federal legislation encouraging research commercialization. Patronage -- the adage, 'he who pays the piper, calls the tune' is a central theme across all epocs and configurations. Only in the national service configuration are federal and state governments the primary patrons of US higher education. In the associational and market configurations, the primary patrons are private households and the private sector. As colleges become more reliant on revenue from tuition and donations, they have systematic about identifying willing patrons with deep pockets.

<!-- CUT TEXT FROM FIRST DRAFT THAT YOU MIGHT USE

We place RDT in dialogue with Stevens and Gebre-Medhin's -@RN4517 three institutional configurations -- associational, national service, and market -- that describe the evolution of US higher education. 

Colleges are dependent on willing stakeholders with deep pockets. 

College Board, a membership organization composed US colleges, has a long history of providing funding and data to researchers from member colleges who are thinking about problems faced by other member colleges. College Board transforms the outputs from these research products into products that they sell to member organizations -- Geomarkets and the Market Segment Model by @RN4982 become College Board's Enrollment Planning Service --  offering concrete examples of how research rooted in the associational configuration is converted into products for the market configuration. 
-->

The "enrollment economy" refers to college reliance on patronage tied to students. This concept was introduced in Clark's -@RN2401 study of California adult education institutions: "The most important pressures on these schools in their day-to-day administration arise from the *enrollment economy* [because] school income is largely determined by student attendance" (p. 332). At the opposite end of the prestige spectrum, the article "Subsidies, hierarchy and peers: The awkward economics of higher education" [@RN1549] describes how selective private colleges depend on students. These organizations utilize a "customer-input" production function: "the technology of producing much of what is sold in higher education is unusual in that colleges can buy important inputs to their production only from the customers who buy their products" (p. 17). Not only do colleges depend on students for tuition revenue and on alumni for donation revenue, but "quality of the education any student gets from college depends in good measure on the quality of that student's peers (p. 17). Furthermore, the characteristics of enrolled students -- for example, average SAT scores -- substantially determine their national ranking, which then determines student demand for the subsequent cohort of prospects [CITE] and also affects research funding and donation revenue [CITE].
<!--
@RN2401[p. 335] observes that "their central dilemma is that the short-run need for clientele, set by the enrollment economy, strains against the long-run need for educational respectability as the basis for legitimacy." 
-->

We sketch the enrollment economy for our analysis sample. We include 12 selective private liberal arts colleges, ranging from Williams and Swarthmore -- ranked \#1 and \#3 respectively in the 2020 USNWR liberal arts college in 2020 USNWR -- to Sewanee (ranked \#47) and Connecticut College (ranked \#51). The enrollment economy for selective liberal arts colleges hews most closely to the characterization of @RN1549. Their position in the zero-sum game for prestige is largely dependent on the high school academic achievement of the students they enroll, rather than the achievement of the faculty they employ. These institution depend primarily on revenue from tuition and donations from wealthy alumni. Increases in federal student loan maximums and the growing use of home equity lines of credit facilitated long-term growth in tuition prices and an arms race in spending on education quality and amenities [@RN4461; @RN5066]. Given the high price of tuition and the desire to enroll students from families who will donate in the future, selective liberal arts colleges primarily enroll rich students with a modicum of students from middle- and lower-class backgrounds [@RN4722]. However, only a handful of colleges enjoy strong demand from high achieving, affluent students. Outside the top ten, the priority becomes "affluent families [who] could absorb the College's full tuition and boar costs with little, if any, financial aid" [@RN3519, p. 73; @RN3522]. Selective private research universities face a similar enrollment economy, but are less dependent on students to the extent that they derive financial and reputional resources from faculty research. Our analysis sample includes 14 selective private research universities, with Northwestern (ranked \#9) and Notre Dame (ranked \#19) at the top and Stevens Institute of Technology (ranked \#80) and Marquette (ranked \#88) at the bottom. 

Our analysis sample includes 16 public research universities, ranging from UC-Berkeley (ranked \#22) to the University of Arkanas (ranked \#160). Historically, public research universities were less beholden to the enrollment economy than private colleges due to federal research funding and block-grant funding from state appropriations. Most were content to rely on enrollment from state residents. State appropriations became less certain, starting in the 1980s [@RN2271]. RDT suggests that organizations respond to initial resource instability from an important provider by signaling the value they provide [@RN1095]. State appropriations became increasingly volatile in the 2000s, declining substantially during economic downturns, but failing to rebound during periods of recovery [@RN2271]. In response to prolonged declines from an important provider, RDT suggests that organizations reduce dependence on the resource provider by seeking new sources of patronage. State disinvestment in public higher education, coupled with price ceilings for resident tuition, compelled public flagship universities to pursue nonresident enrollment as a substitute for state appropriations [@RN3753].^[From 2002-03 to 2012-13, a 10% decline in state appropriations was associated with a 4.6% increase in subsequent nonresident freshman enrollment @RN3753] Nonresident students tend to be more affluent than resident students [@RN3685]. Therefore, state disinvestment makes public research universities beholden to the enrollment economy that governs selective private research universities, pursuing national recognition rankings and/or intercollegiate athletics as a means of generating demand from affluent households willing to pay the higher price of nonresident tuition.
<!--
^[@RN1095 shows how the University of Wisconsin-Madison attempted to justify and sustain public funding from the state.]
-->



<!-- 
Scholarship at the nexus of EM and college access can be categorized by which part(s) of the enrollment funnel it speaks to. The enrollment funnel -- shown in Figure @fig-em-funnel and based on the traditional marketing funnel -- is a conceptual model used by the EM industry to depict stages in the process of recruiting students [@RN4986; @RN2004]. The funnel begins with a large pool of "prospects" (the universe of prospective students the college would like to enroll), followed by "leads" (prospects whose contact information has been obtained), "inquiries" (prospects who contact the institution), "applicants," "admits," and "enrolled students." The funnel narrows at each successive stage in order to convey the assumption of "melt" (e.g., a subset of "inquiries" will apply). The purpose of the enrollment funnel is to inform recruiting interventions that target one or more stages. These interventions seek to increase the probability of "conversion" across stages [@RN4322]. In sociology, economics, and related interdisciplinary fields, the majority of scholarship focuses on the admissions stage -- for example, analyzing which admissions criteria are utilized and/or which applicants are admitted [e.g., @RN4874; @RN4993; @RN4131; @RN3522] -- or on financial aid leveraging as a means to convert admits to enrolled students [e.g., @RN3133; @RN3762]. For example, @RN2241 shows that from 1992 to 2003, the amount of institutional financial aid awarded on behalf of student financial need decreased relative to financial aid awarded to student academic achievement.
-->

The most basic statement of RDT is that organizational stability depends on maintaining a predictable flow of important resources from the external environment [@RN959]. For colleges in the enrollment economy, organizational organizational stability is the responsibility of enrollment management (EM). The EM profession integrates techniques from marketing and economics in order to "influence the characteristics and the size of enrolled student bodies" [@RN2771, p. xiv]. Colleges depend on a stable flow of incoming students that satisfy broad enrollment goals [@RN2772] -- related to revenue, academic profile, and diversity -- and the granular demands of internal constituents [@RN3519] -- for example, the biology department needs majors and the band needs players. 

Colleges depend on high schools to provide these students. Although a college does not depend on any single high school to provide a substantial share of enrollment, the list of schools that enroll desirable students who are interested in attending is finite, thereby motivating "the recruiters' emphasis on feeder high schools" [@RN4982, p. 11]. High schools want to send their students to college. This goal is particularly important at affluent public high schools and even more so at expensive private schools, which depend on their record of sending students to "good" colleges to rationalize the sticker price. @RN960 states that dyadic relationships typically involve mutual dependence between actors, but that relationships of mutual dependence are seldom symmetric. A college values a high school to the extent that they want to enroll students from that high school. A private college that depends mostly on tuition revenue may place low value on a high school that primarily enrolls low-income students. A high school values a college to the extent that they want some of their students to enroll in that college. The distribution of student achievement suggests that high schools value a range of colleges. However, colleges deemed below this range may be viewed with disdain.

As an administrative structure, the "office of enrollment management" typically controls and coordinate the functional activities of admissions, financial aid, and recruiting [@RN2406; @RN3625]. The administrative structure of EM offers one means of categorizing scholarship about EM. In sociology, economics, and related interdisciplinary fields, the majority of scholarship focuses on admissions [e.g., @RN4874; @RN4993; @RN4131; @RN3522] or financial aid [e.g., @RN3133; @RN3762]. A growing literature in sociology analyzes the earlier "recruiting" stages of acquiring "leads," and soliciting "inquiries" and applications. Several monographs analyze recruiting as part of a broader study on enrollment management [@RN3519], high school to college transitions [@RN4324], elite reproduction [@RN4407], or political economy [@cottom2017lower]. We situate this research within scholarship on recruiting that focuses on linkages between colleges and high schools.

@RN959 describe inter-organizational linkages as a tool for managing dependence on resource providers that the organization cannot acquire or substitute. Whereas professional associations (e.g., American Council on Education) create links between direct competitors beholden to a common resource provider (often the government), cooptation is the strategy of an organization establishing relationships with particular resource providers in order to socialize the resource provider to the goals of the organizaton. Drawing from @RN3519 and @RN4321, the relationship between college admissions officers and high school guidance counselors is one of mutual cooptation. The admissions officer tries to convince the guidance counselor of the special mission/character of the college, hoping the guidance counselor steers students to the college. The guidance counselor tries to convince the college admissions officer of the special value of the school's students, especially students deemed marginal by conventional measures of academic achievement [@RN4321].^[@RN4321 describes how high school guidance counselors at elite private schools exploit the enrollment goals of selective colleges in order to "get comparatively under-qualified students into top colleges and universities" (p. 98). Admissions officers at selective colleges want to know whether an applicant would enroll if granted admission because admissions and yield rates are inputs of USNWR rankings. This desire for credible information creates an opportunity for high school counselors to advocate on behalf of their students. Guidance counselors tell admissions counselors which highly-sought-after applicants are likely to decline an offer, while lobbying for an applicant who has relatively weak academic credentials but is sure to matriculate and has "character" and extracurricular activities demanded by internal constituents of the college.]

@RN3519 provides an ethnography of enrollment management at a selective private liberal arts college. Being tuition-dependent and sensitive about its position in the rankings, The College focuses on enrollment goals related to academic profile and revenue generation. @RN3519 highlights the relational function of off-campus recruiting visits: "the College's reputation and the quality of its applicant pool are dependent upon its connections with high schools nationwide" (p. 54). During the autumn "travel season," admissions officers visit selected high schools across the country "to spread word of the institution and maintain relationships with guidance counselors" (p. 53-54). @RN4741 reported that "calling high school counselors after visits" was an effective and widely-used outreach strategy for both private universities and public universities. Thus, relationship maintenance remains a high-touch process even in the digital age.
The College tended to visit the same "feeder" schools year after year because recruiting depends on long-term relationships. Visited schools tend to be affluent schools -- in particular, private schools -- that possess the resources to host a visit and enroll high-achieving students who can afford tuition.

Whereas scholars in the sociology of education have investigated recruiting as part of a broader analysis, AUTHORS [-@RN4758; -@RN4759; -@RN5023] have attempted to develop a literature about recruiting. @RN4758 argue that off-campus recruiting visits are a credible indicator of college enrollment priorities because recruiting visits cost resources and because visits to individual schools are largely invisible to macro stakeholders.^[Sociological theories of organizational behavior argue that organizations expend substantial resources on goals they care about while symbolically adopting -- highly visible, ceremonial behavior with few resources expending -- goals demanded by stakeholders in the broader institutional environment.] @RN4758 analyzed recruiting visits made by public research universities. The authors found that 12 of the 15 universities made more visits to out-of-state schools than in-state schools. These out-of-state visits focused on affluent, predominantly white public high schools. Set against scholarship about nonresident enrollment growth as a response to declining state support [@RN3753; @RN3685], these results suggest that many public research universities prioritize enrollment from wealthy out-of-state students. 
<!-- 
Many colleges list their "travel schedule" on their admissions page. As described below, @RN4449 collected data about off-campus recruiting visits made during the 2017 calendar year from a (non-random) sample of public research universities, selective private research universities, and selective private liberal arts colleges by scraping these data from their admissions pages.
-->

@RN5023 conduct a social network analysis of recruiting visits to private high schools by a sample of public research universities and selective private research universities. They conceptualize visits as an indicator of a social relationship between a college and a high school, indicating that the college wants to enroll some students from the high school and that the high school wants to send some students to that college. Universities in the sample made a disproportionately large number of visits to private high schools relative to public high schools. Analyses revealed substantial overlap in the direct recruiting networks of public and private universities. @RN4759 conducted geospatial analyses of out-of-state recruiting visits to Los Angeles and Dallas by four public research universities. She found that universities engage in "recruitment redlining -- the circuitous avoidance of predominantly Black and Latinx communities along recruiting visit paths" (p. 585).

We argue that scholarship on enrollment management has gone astray by focusing on college behavior as the source of racial and socioeconomic inequality in college access. Empirically, this literature focuses on the behavior of individual colleges. In turn, the literature assumes that enrollment management behavior is a function of individual college preferences, which are conditioned by logics and forces in the organizational field (e.g., rankings, state funding). @RN5070 makes a similar observation about the sociology of gender in her analysis of insurance products, stating that feminist scholars considered gender discrimination an "organizational matter -- a product of administrative routines such as hiring procedures, promotion protocols \ldots [but] this approach reinforced the notion that markets do not themselves contribute to discriminatory outcomes." We argue that scholarship on enrollment management has failed to consider third-party intermediaries that classify students on behalf of colleges.
<!-- 
We present the case of Geomarkets and The Market Segment Model, which classified students and localities on behalf of colleges looking for customers.-->

# Devices, Commensuration, Classification

## Geomarkets and the Market Segment Model

We describe the case of Geomarkets and the Market Segment Model, adding deeper context as we introduce concepts from market devices, commensuration, and ordinal classification. Geomarkets were conceived in the late 1970s, when colleges were concerned about declining demographics. @RN4982[p. ix] write that demographer "Stephen @RN5076 had already frightened everyone who would listen with his projection of 40-percent declines in college enrollments by the close of the 1980s." Elite colleges responded by leaning on the associational configuration [@RN4517] to solve problems common to the group. The project began when UPenn president, Martin Meyerson, tasked UPenn professor Robert Zemsky, to figure out, "'Who thinks about Penn?'" and "'What other institutions do they think about when they think about us?'" [@RN4982, p. x]:

> "In pursuit of these questions, we began working in 1978 with the Market Research Committee of the Consortium on Financing Financing Higher Education (COFHE). The Consortium, a group of thirty selective private institutions, had in its brief history developed a remarkable tradition of sharing data\ldots For nearly a year, the Consortium's Market Research Committee provided focus to our efforts. Much of this project's framework -- the Market Segment Model and its derivation from admissions officers' folklore was shaped and then reshaped in our discussions with members of the committee."

<!-- FULL QUOTE
> "In pursuit of these questions, we began working in 1978 with the Market Research Committee of the Consortium on Financing Financing Higher Education (COFHE). The Consortium, a group of thirty selective private institutions, had in its brief history developed a remarkable tradition of sharing data. Members of COFHE had come to know almost as much about one another's applicant pools as they did about their own. For nearly a year, the Consortium's Market Research Committee provided focus to our efforts. Much of this project's framework -- the Market Segment Model and its derivation from admissions officers' folklore was shaped and then reshaped in our discussions with members of the committee."
-->

The Market Segment Model is the product of practioner-derived market research. In the 2000s, College Board created the *Segment Analysis Service* product [@RN4565] as an application of geodemographic market research logics -- associated with mail-order catalogs -- to the case of college choice [@RN4957]. By contrast, @RN4982 conceived of the Market Segment Model as an effort to "capture and quantify" (p. 11) the knowledge of admissions officers: 

> Admissions officers invariably are tellers of stories -- about the colleges they represent, about the colleges they attended, about each other, and about the often vagabond life of college recruiting\ldots We have begun with this celebration of storytelling\ldots \[because\] we believe that the intuitions of admissions officers actually comprise a remarkably systematic body of knowledge about the college selection process\ldots Our research is based upon listening carefully to what admissions officers have to say (pp. 9-10).

The "initial [analytic] task" was to define geographic boundaries "in a manner consistent with admissions officers' intuitive understanding of student pools" [@RN4982, p. 4]. Quoting an admissions officer, @RN4982 \[p. 11\] write, "'There are only three kinds of college-bound students: those who want to live at home, those who want to live on campus but bring their laundry home, and those who want to go far enough from home that Mom and Dad can't visit without calling first.'" As such, @RN4982 [p. 11] created "three types of boundaries -- region, state, and community." The initial regions in the project were New England, Middle States, and the South. Next, they "divided each state into as few as two and as many as thirty community-based enrollment markets or pools, for a total of 143 separate markets" (p. 11). These enrollment markets, later called Geomarkets, were intended to be consistent with the conception of a catchment market from the perspective of admissions counselors. @RN4982 [pp. 11-12] described the creation of Geomarket borders only briefly:

> In many cases, the market boundaries match formal political and educational divisions, reflecting natural channels of communication. Each major metropolitan area is composed of several markets, usually corresponding to the inner city, a first ring of suburbs, and an outer ring of suburbs. In more sparsely populated areas, communities are sometimes combined in order to make the analysis meaningful.

Over time, the project goal morphed into predicting student demand for any college from any locality. However, "to gain a truly comprehensive view of the collegiate enrollment market, we needed a database that described most institutions and most students" [@RN4982, p. x]. The group approached College Board. "Coincidentally, the Board was reviewing its own efforts to help colleges estimate their enrollment potential" [@RN4982, p. x]. College Board provided score-sending data for all 1980 SAT test-takers. For a given student, each college that receives a score from the student can be defined as "local" (college located in the the same Geomarket as the student), "in-state" (same state but different Geomarket), "regional" (same region but different state), or "national" (different region). @RN4982 classified each SAT test-taker into one of four student *market segments*. A student is categorized in the "local" market segment if they submit more SAT scores to local institutions than they do to in-state, regional, or national institutions. An "in-state" student submits more SAT scores to in-state institutions than they do to local, regional, or national institutions, etc. The Market Segment Model "was nothing more than a set of simple rules for disaggregating high school seniors into similar groups" [@RN4982, p. 4]. "The model worked because students, once so disaggregated, appeared to behave in remarkably consistent ways."

@RN4982[Chapter 3] investigates which student characteristics predict whether a student belongs to the local, in-state, regional, or national market segment. The analyses identify four variables -- educational aspirations, parental education, scholastic aptitude, and family income -- that predict score-sending behavior, both individually and in combination. The resulting thesis is that student demand for college is a function of social origin. These four variables "reflect the basic social patterns of the nation; it would have been surprising if these were not the four social variables that best explained the patterns of college choice" [@RN4982, p. 33]. The analyses conclude (p. 42) that "our research has simply demonstrated what everyone has always known: communities with high levels of family income and parental education are also communities in which students have higher than average SATs and more far-reaching aspirations." 

However, Geomarkets differ in the relative abundance of students with particular socioeconomic characteristics. As college leaders sought new sources of patronage, the Market Segment Model yielded practical implications about which communities to target. @RN4982[p. 44] recommend that colleges target Geomarkets with desirable compositions of socioeconomic characteristics in order to reach students from desired student market segments:

> On occasion, senior spokespersons for the profession worry that students outside the main \[Geo\]market areas remain forgotten and hence, unchallenged. Inevitably, the increasing competition for students, the expense of travel and mailings, and internal political constraints compel institutions to concentrate their efforts where they will do the most good. The result is a natural reinforcing of the basic socioeconomic patterns that gave shape in the first place to the structure of college choice.

*Market devices*. We conceive of Geomarkets, the Market Segment Model, and the subsequent Enrollment Planning Service Software as interrelated "market devices" [@RN5064; @RN5067]. Market devices are the assemblage of techniques, theories, and culture that make economic action possible [@callon1998embeddedness]. Drawing from Krippner’s -@RN5070 study of insurance, an example of a market device is the statistical models that assign individuals to "risk pools" for insurance products. Market devices shift scholarly attention to the individual components -- including techniques, theories, cultural logics, and histories -- that are foundational to products and to markets [@RN5071] The analysis of market devices in insurance also includes the long history of mutualism that the insurance industry emerges from. Market devices are also useful because they shift source of social inequality from organizations to markets. @RN5070 argues that the statistical models underlying insurance products are "gendered market devices" because gender is one of the variables used to assign people to different risk pools.

Market devices build on market devices. The SAT is a market device that enables colleges to compare students from different schools. Students can send SAT scores to colleges they are interested in. The Market Segment Model is a theory of student demand that categorizes students into different market segments based on SAT score-sending behavior. Geomarkets are a market device that simultaneously defines geographic localities and compares these localities based on the number of students from each market segment. Geomarkets are then incorporated into the Enrollment Planning Service product and the Student Search Service product.


<!-- THIS IS THE CUT TRANSITION PARAGRAPH
Building on @RN4810, we argue that Geomarkets and the Market Segment Model form a social-classed market device 

[SAY THAT SCHOLARSHIP ON ENROLLMENT MANAGEMENT] Similarly, scholarship on enrollment management tends to locate inequality in the behavior of colleges [@RN4758]. This literature has engaged with market devices -- particularly rankings -- that affect college behavior by changing consumer preferences [CITE], but has not considered market devices that 

Similarly, scholarship on enrollment management locates inequality in the behavior of colleges  ignores inequality that is produced by market devices. 
Whereas @RN5070 analyzes market devices embedded in consumer-facing products (auto insurance, life insurance), we analyze market devices that structure the recruiting behavior of colleges.
-->

Analyzing the 1970s origins of Chicago's financial derivatives market, @RN5067 observed that the creation of new market devices requires collective action amongst interconnected members with shared goals and shared cultural understandings, those "classic themes of economic socoiology" (p. 109). Market devices often carry the culture of status groups that create them [@RN5070; @RN5071]. @RN3547 shows how the Protestant upper class status group that controlled Ivy League colleges in the early 20th Century achieved social closure by developing "character" admissions criteria, a sort of market device that effectively excluded Jews. The Market Segment Model was created and supported by COFHE and College Board, membership associations led by upper-class white men with strong ties to elite private colleges. Unsurprisingly, @RN4982 argues that student demand for college is a function of social class and, in turn, social class is the organizing principle of competition between colleges: 
<!-- SALIENT TEXT FROM PAGE 45 IF YOU WANT TO KEEP IT

Most admissions officers\ldots intuitively understand that students think not so much of individual institutions as of groups of institutions. In the words of one veteran dean of admissions, 'We are known primarily by the company we keep.' For this reason, colleges actually encourage competition wwith one another to define their places in the market. Members of the Consortium of Financing Higher Education (COFHE) -- a group of thirty highly selective, high-cost, private institutions -- regularly exchange detailed and confidential information about their applicant pools, admissions strategies, and financial aid programs. What every envious admissions officer outside the Consortium understands is that these thirty institutions are strengthened by their collectivity, though they are in fact one another's principal competitors.
-->

Performativity describes the effects of market devices. Performativity is the idea that market theories and associated metrics do not merely describe behavior, but rather they actively bring about behavior consistent with the theory [@RN5064]. The concept performativity is related to the concepts reactivity, discipline, and authority in the quantification literature [@RN5007], which has utilized college rankings as a case [@RN5003].^[Three effects quantification are reactivity (people and orginizations change behavior in response to salient quantitative measures), discipline (quantification disciplines actors to react in particular ways), and authority (quantification often weakens discretion of local decision-makers) [@RN5007]. The canonical case is USNWR law school rankings [@RN5003; @RN2356; @RN2376; @RN2375], which were developed as a mechanism to inform students about the prospective students about the relative quality of different programs. Rankings had the intended consequence of affecting (reactivity) where students apply and enroll [@RN5003]. Rankings also affected hiring decisions of firms because clients evaluated firms based on the prestige of law schools attended by firm lawyers. Once law schools realized that important constituents "used rankings to make decisions that had large consequences for schools" [@RN5007, p. 415], rankings disciplined the behavior of law schools. For example, characteristics valued by the rankings system (e.g., LSAT scores) became more important for decisions about admissions and merit aid. Rankings also weakened the *authority* of admissions personnel to make independent decisions about class size and which applicants to admit [@RN5003].] As an example of performativity, @RN5067 provide a historical sociology of the Chicago Board Options Exchange, which opened in 1973. An option is a contract that gives the holder the right to buy or sell an asset (e.g., a stock) at a given price. Federal regulators viewed options markets skeptically, as "wagers on price movements" [@RN5067, p. 113] that had contributed to the Great Depression. Economists Fischer Black and Myron Scholes developed the Black-Scholes model to predict the price of options @RN5074, eventually winning the Nobel Prize in Economics. This work provided legitimacy to options markets as a means of efficient pricing rather than speculative gambling. Initially, the Black-Scholes model did not accurately predict the price of options. Black-Scholes model predictions became more accurate over time because options traders began embedding the logic and components of the model into spreadsheets/software; the model became more accurate because the model produced the prices it predicted [@RN5067]! Similarly, the Market Segment <Model -- a class-based theory about the geography of student demand -- was built into EPS software that colleges utilized to plan their travel schedule [@RN4980].





*Commensuration*. We also draw from scholarship on commensuration [@RN5071; @RN5063]. Commensuration is "the expression or measurement – of characteristics normally represented by different units – according to a common metric" [@RN5063, p. 315]. Commensuration is a process that requires work, akin to institutionalization. Once achieved, commensuration has the effects of opinionated expedience, that is, useful but with side effects. College rankings are an example of commensuration with side effects. Commensuration reduces the cognitive effort of decision-making. It is "a way to reduce and simplify disparate information into numbers that can easily be compared. This transformation allows people to quickly grasp, represent, and compare differences" (p. 316). The process of commensuration identifies a quantitative metric that aids comparison, discarding the heterogenous collection of material that could be the basis of comparison. Therefore, commensuration "can be understood as a system for discarding information and organizing what remains into new forms" [@RN5063, p. 317]. @RN5071 describes money as a tool of commensuration; an object that can be valued by money can be compared to any other object that can be valued by money.^[@RN5071 compares two famous oil spill cases -- Amoco Cadiz on the coast of Brittany, France and the Exxon Valdez in Alaska -- valued "nonuse" damage to the environment. The Exxon Valdez relied on "nonuse damage valuation methods" and awarded huge settlements. The Amoco Cadiz case conceived of the envoronment as priceless and therefore incommensurate with money, resulting in no such monetary award.] "Embedded in this logic is another assumption," @RN5063[p. 324] that all value is relative and that the value of something can be expressed only in terms of its relation to something else." Things that cannot be expressed in terms of something else will not be valued.
<!--
@RN5071 compares two famous oil spills, the Amoco Cadiz on the coast of Brittany, France and the Exxon Valdez in Alaska. The loss of fisheries could be valued using established theories of economic use. How should courts value the loss of nature? What is the economic value of nonuse? In the Amoco Cadiz case, courts ultimately decided that nature could not be valued. Environmental groups aided this decision, arguing that the environment is priceless and therefore incommensurate with money. "Incommensurables preclude trade-offs" write @RN5063[p. 326], "An incommensurable category encompasses things that are defined as socially unique in a specific way: they are not to be expressed in terms of some other category of value." In the Exxon Valdez case, plaintiffs drew from innovations in environmental economics, which had developed "nonuse damage valuation methods" [@RN5071, p. 1759]. This approach led to Exxon paying \$2 billion in civil charges, compared to \$0 paid by Amoco, even though the Amoco Cadiz spill was larger and in a more densely populated area. "Embedded in this logic [of commensuration] is another assumption," @RN5063[p. 324] that all value is relative and that the value of something can be expressed only in terms of its relation to something else. Things that cannot be expressed in terms of something else cannot be commensurated and will not be valued.
-->

The analysis of UK school "league tables" by @RN5005 portrays commensuration as a mechanism of social reproduction. In 1992, the UK government began publishing school league tables that ranked schools on student performance on national exams taken at age 16. League tables disciplined households -- and in turn schools -- to conceive of school quality in terms of test scores. League tables facilitated making evaluative comparisons between schools regardless of geographic proximity, but only in terms of the test score metric that was substantially a function of the class composition of schools. Following the adoption of league tables, localities with higher performing schools experienced growth in the share of managerial/professional households and a decline in the share of working-class households [@RN5005]. The introduction of league tables contributed to social reproduction because professional/managerial households were more aware of these consumer-facing metrics and had resources to respond by moving to more expensive neighbhorhoods, near higher performing schools. 
<!-- THIS IS THE CUT TRANSITION PARAGRAPH
Schools that performed well on initial league tables tended to be schools with a high share of professional/managerial families. Therefore, quantification takes a snapshot of existing social stratification and that snapshot becomes a power unto itself, amplifying the effect of previous strctural inequality on subsequent structural inequality.
-->

Both sociology and economics conceive of the SAT as a market device that facilitates commensuration. Economist Caroline @RN2247 argues that "information costs" were a barrier to the emergence of a national higher education market that efficiently matches students to collges: "In 1955, there was no early national college aptitude test. Students and colleges simply did not know where students stood in the national distribution of high school graduates’ achievement or aptitude" (p. 103). Colleges could not make an apples-to-apples comparison between students from different schools because the information on a high school transcript "is relative to a standard that a college will not understand unless it draws very often from the high school" (p. 103). @RN2247 credits the SAT/ACT exams for the emergence of an efficient, national higher education market.^[From 1955 to 1990, the number of colleges requiring the SAT/ACT increased dramatically from 143 to 1,839, while the number of SAT/ACT test-takers per freshman seat increased from 0.23 in 1955 to 0.87 in 2005.] Institutionalization of the SAT/ACT caused a "dramatic fall" in the cost of "colleges’ information about students" [@RN2247, p. 102]. From the perspective of sociology, however, this process of commensuration de-emphasized the importance of students' varied abilities, backgrounds, and interests relative to a single test score [@RN3536]. 

We conceive of Geomarkets as a commensurating market device that builds on the SAT. @RN4982 created Geomarkets for the purpose of comparing different geographic recruiting territories. Consider the "MA10 -- Milton, Lexington, Waltham" Geomarket versus "NJ10 -- Bergen County." How should we compare them, by population density, household income, their history of segregation? @RN4982 developed the Market Segment Model, which created four student segments: "local" students, who primarily sent SAT scores to colleges in their home Geomarket; in-state students; regional students; and national students, who set SAT scores primarily to colleges outside their home region (e.g., New England). Whereas UK league tables allowed parents to compare geographically disparate schools based on test scores [@RN5005], the Market Segment Model enables enables colleges to compare geographically proximate and geographically disparate Geomarkets based on the number of students from each market segment.^[The number of 1980 test-takers was a limiting factor in deciding what constitutes a single Geomarket. For example, @RN4982[p. 12] writes "In more sparsely populated areas, communities are sometimes combined in order to make the analysis meaningful."] @RN4982 states that selective colleges primarily draw students from the regional and national market segments. The key to finding new student markets, then, is identifying Geomarkets with large numbers of regional and national students. This information could be obtained from College Board EPS software.
<!-- BELOW CUT IDEA IS CENTRAL TO THE PAPER -- NEEDS TO BE SOMEWHERE -- BUT IS NOT 
Furthermore, it turned out that student market segment is primarily a function of social class [@RN4982]. Therefore, Geomarkets with large numbers of regional and national students were also home to affluent households that contributed to the economic patronage goals of the selective college enrollment economy.
-->

We draw from scholarship on ordinalization and classification situations [@RN4810; @RN5015; @RN4808; @RN5072]. @RN5072 defines three kinds of classification: *nominal* classifications, oriented to qualitative essense or "type" -- such as race, gender, country of citizenship, or biological taxonomies; *cardinal* classifications, oriented to quantities and magnitude (e.g., SAT score), where differences between quantities can be measured exactly but only for objects within the same nominal classification; and *ordinal* classifications, which are oriented to relative positions that can be hierarchically ranked, but the distance between positions are not measured quantitatively. @RN5072 describes the growing prevalence and importance of ordinal classifications. Objects once considered incommensurate because they are different categories of a nominal classificationcan now be ranked. For example, the autism spectrum replaces the distinct categories of Asberger's and autism. @RN5072 argues that the transformation from nominal to ordinal categories serves political liberalism because ordinal classifications are more inclusive. The democratization of credit is hierarchical. The college-for-all movement is associated with replacing the nominal binary of a college student with more inclusive, but ordinal classifications that ranges from the part-time adult learner in a community college to full-time Ivy League students.


@RN4808[p. 9] argue that contemporary organizations follow a "data imperative to collect as much data as possible." Historically, data were recorded manually by people writing in ledgers or by collecting survey data [@RN4808]. Contemporary "administrative data" are recorded automatically as a function of people engaging in transactions and being observed by devices. Data are collected with and without a use in mind, sold and resold to data aggregators, combined with other data sources, and incorporated into analyses that classify people and/or predict behavior [@RN4744; @RN4799; @RN5061].

<!-- 
@RN4808 contemporary markets obtain data about people and analyze these data to inform interventions. First, the "data dragnet" produces data about individual consumers from many sources. Historically, data were recorded manually by people writing in ledges or by collecting survey data [@RN4808]. Contemporary "administrative data" -- to use the social science term -- are recorded automatically as a function of people engaging in transactions and being observed by devices. Data are collected with and without a use in mind, sold and resold to data aggregators, combined with other data sources [@RN4744; @RN4799]. The second stage is analyzing these heterogeneous data into classifications, scores, and predictions. One example is the platforms for policing developed by Palantir, which incorporate diverse data sources -- structured, semi-structured, and unstructured -- to yield predictions about where crime will occur, to alert officers of events, and to query across diverse databases [@RN5061]. 
-->

The Market Segment Model offers an early example processes described by @RN4808. College Board collects data from students laboring on their platforms. Students manually record data by taking a test and by completing pretest survey questions (demographics, grades, social class, intended major). These data are repurposed into several products.^[Examples include the *Student Search Service* and the *Admitted Student Questionnaire*.] Students may send test scores to colleges they are interested in, a long-standing feature of the SAT product. Data on score-sending behavior are administrative data collected as a function of organizational operations. @RN4982 created the Market Segment Model based on 1980 score-sending data provided by College Board. @RN4982 developed two analytic outputs: (1) The Market Segment Profile -- for each Geomarket, the number of students from each market segment, their socioeconomic characteristics, and average test scores; (2) The Institutional Profile -- for a given institution (your own or a competitor) and Geomarket, how many students from each market segment sent scores to that institution. In 1984, College Board transformed the Market Segment Model and associated outputs into the Enrollment Planning Service (EPS) software-as-service product, which helps colleges identify desirable Geomarkets and high schools for recruiting.

The data imperative and subsequent algorithms yield ordinal interventions called "classification situations" [@RN4810], whereby organizations "sort and slot people into new types of categories with different economic rewards or punishments attached to them" (p. 561). Classification situations intervene on the concept of class. Sociology has defined social class by the production side of the economy (e.g., worker vs owner; clerical, manager, professional). By contrast, @RN4810 argue that contemporary processes of ordinalization "endogenous to the market" (p. 560) define class through effects on the *consumption* side of the economy. The canonical example is credit scores [@RN4877], which enable third-party intermediaries on supply side to "slice consumers into behaviorally-defined risk groups, and price offerings to them accordingly. On the demand side, consumers find themselves \ldots fitting into these categories—which, by design, are not constructed from standard demographic classifications such as race" [@RN4810, p. 560] though they are highly correlated with social categories. The goal of classification situations is "good matches," whereby an ordinal hierarchy of products match to an ordinal hierarchy of people. Businesses "seek good matches when they want to link a wealthy customer with a quality credit card, or a heavy drinker with a bad insurance plan" [@RN4808, p. 17]. The economics of education views such matches positively: the "efficient outcome allocates students to colleges based on students’ ability to benefit from the \ldots magnitude of the human capital investment that the college offers" [@RN2247, p. 106]. Sociology is more skeptical [@RN4774], highlighting the predatory, extractive inclusion of formerly excluded consumers (e.g., for-profit colleges).

<!-- PUT THIS BELOW INSTEAD
Classification situations intervene on the concept of class. Marx argues that class is defined by the production side of the economy, highlighting the binary of worker versus owner [@RN1423]. The social stratification literature introduce a spectrum of social class still largely defined by occupation (e.g., manager, professional) [e.g., @RN915], with the notable inclusion of educational attainment. 
[@RN4808, p. 17]:

> Companies seek good matches when they want to link a wealthy customer with a quality credit card, or a heavy drinker with a bad insurance plan. This kind of matching capitalizes on people’s differentiated dispositions and practical habits, what Pierre Bourdieu calls their habitus. The ‘good matches’ are perceived as natural because they fit well with how things already are.
-->

<!-- The Market Segment Model is a class- and geography-based theory of student demand that classifies consumers (prospective students) on behalf of consumers (colleges).  -->

We conceive of Geomarkets and the Market Segment Model as an ordinal market device that amplifies inequality by matching a socioeconomic hierarchy of places to a socioeconomic hierarchy of colleges.^[Whereas @RN5015 analyze devices that classify individuals, the Market Segment Model harkens back to the earlier era of geodemography, in which market research classified places for merchants based on the attributes of people who lived there [@RN4880; @RN4957]] @RN4982 defined student market segments on ordinal terms -- local, in-state, regional, and national -- and found that student market segment was primarily a function of class (parental income and education). @RN4982 also conceived of colleges as an ordinal hierarchy. As in [FOURCADE], Good matches are the key to enrollment. Good matches are defined by homophily, the idea that actors who share common characteristics are likely to form connections with one another [@mcpherson2001birds; @RN4975]. @RN4982[chapter 4] conducts a network analysis whereby two colleges are defined as competitors if a large number of students submit SAT scores to both colleges. @RN4982[p. 46] "draw a fundamental conclusion about the structure of college choice: collegiate competition occurs principally between like institutions." Subsequent analyses investigate the tuition price and the socioeconomic composition of institutions in competition with one another. The takeaway is that like-colleges compete for like-students as defined by social class, with private selective colleges competing directly for students, charging the highest prices, and enrolling students with the highest socioeconomic status (p. 72):

> Students describe themselves socially simply by telling us the colleges and universities in which they are interested. The layering of collegiate competition is primarily a socioeconomic layering. The hierarchical structure of collegiate competition largely reflects the stratified social and economic dimensions of the communities from which colleges draw their students. Competition among colleges, as admissions officers have told us for so long, is in fact, a matter of keeping company with one's peers.


Scholarship about third-parties that mediate between consumers and producers/sellers considers two broad types of intermidiaries: intermediaries "that occupy the interface between consumers and producers" [@RN5065, p. 1], including college rankings and expert critics; and intermediaries akin to the "classification situations" of @RN4810 that classify consumers on behalf of sellers. We might cede that  consumer-facing product ratings have more pathways of influence; they discipline consumer preferences, which in turn disciplines product attributes created by producers. On the other hand, intermediaries that classify consumers for the sake of producers -- including the entire field of market research -- are much more sophisticated [@RN4957; @RN5064; @RN5073; @RN4808]. To our knowledge, scholarship on quantification in the sociology of education has mostly focused on consumer-facing intermediaries. Certainly college rankings [@RN5003] and school rankings [@RN5005; @RN5075; @hasankumar2019Digitization] are salient for decision-makers and have important consequences. Perhaps another reason for the volume of scholarship about consumer-facing intermediaries is that coverage by the popular press makes them known to researchers. Intermediaries that classify consumers for businesses receive scant attention from the popular press but may highly salient for professionals who are responsible for identifying and recruiting customers.
<!--
To our knowledge, scholarship on quantification in the sociology of education has mostly focused on consumer-facing intermediaries [e.g., @RN5005]. Reviewing scholarship on quantification, @RN5006 argue that quantification has effects to the extent that decision-makers care about the numbers being produced.
-->


Robust literatures in the sociolology of organizations [@RN4421] and the sociology of education [@fast2025racializeddecoupling; @RN5055; @RN4873] shows how the behavior of organizations reproduces racial, class, and gender inequality [CITE]. @RN5070 contributes to scholarship on gender inequality because scholarship that locates inequality in organizational behavior fails to observe gender inequality produced by the market. @RN4873 casts colleges as sorting machines that incorporate and reproduce social inequality. This line of research fails to consider how the market devices utilized by colleges incorporate and reproduce social inequality. Whereas @RN5070 shows that market devices produce social inequality by directly classifying consumers, this manuscript investigates how market devices reproduce inequatlity of opportunity by disciplining how colleges classify consumers.


## Research questions and expected results

Our overarching research interests speaks to the performativity effects of Geomarkets and the Market Segment Model, asking what is the relationship between College Board Geomarkets and high school recruiting visits of selective private colleges and public research universities? Although we lack the longitudinal recruiting data necessary to make causal assertsions, we investigate whether the cross-sectional recruiting visits patterns are consistent with expectations from theory.
<!--
We cannot make causal assertions because we lack longitudinal recruiting data that spans before and after the introduction of these market devices.
-->

We disagregate the overarching research question into three concrete questions. First, to what extent do college board Geomarkets (X) explain which high schools receive recruiting visits (Y), after controlling for covariates thought to explain recruiting visits? We address this question first because a null finding would render subsequent questions unnecessary. In themselves, Geomarkets and the Market Segment Model are merely a class-based, geography-based theory of student demand. We argue that Geomarkets explain recruiting visits by colleges because Geomarkets became embedded in college recruiting behavior in two ways. 

First, Geomarkets and the Market Segment model were the basis for the Enrollment Planning Service (EPS), an early software-as-a-service platform that recreated the analyses of @RN4982. For each Geomarket, colleges could obtain Market Segment Report for each local market and the Institutional Profile -- their own and that of competitors. Based on background conversations with EM professionals, EPS software also provided information about the score-sending behavior of individual high schools within each Geomarket. Therefore, colleges used EPS software to decide which Geomarkets to recruit from and which high schools to visit within targeted Geomarkets. Typical @RN5019 marketing material describes EPS as,

> The marketing software that pinpoints the schools and Geomarkets where your best prospects are most likely to be found. With the click of a mouse, EPS provides you with comprehensive reports on your markets, your position in those markets, and your competition. Focus your valuable time and resources on the right prospects.

Following @RN4982, the EPS platform encouraged users to, first, identify promising Geomarkets and, second, to identify desirable high schools for recruiting visits.^[Software documentation by @RN5017 states that "EPS market codes are proprietary market codes owned by the College Board and are used to categorize external organizations and people into geographical areas, mostly in the United States. Some admissions offices use EPS market codes to focus their recruiting efforts in geographic areas in which they believe they will be the most successful."] Quantification has consequences to the extent that the stakeholders care about the numbers [@RN5006]. Market research suggests that EPS was highly salient. @RN5021 reports that in 1995, 37% of 4-year publics and 49% of 4-year privates used EPS, while 41% of 4-year publics and 16% of 4-year privates used ACT's market analysis service product.

Quantification often reduces the decision-making authority of local actors [@RN5007]. The Market Segment Model sought to replicate the aggregate knowledge of local admissions officers. On background, EM professionals told us that EPS software enabled colleges to plan travel without relying on admissions officers having strong local knowledge of their territories. EPS software often recommended visiting the same sets of affluent, high-achieving high schools that were receiving visits from other colleges. We were told that savvier, quantitatively-adept admissions offices used EPS to visit schools that EPS recommended ignoring because there would be less competition for the good students who attended these high schools. 
<!--Once this knowledge was quantified and commodified onto a CD-ROM, the local expertise of admissions officers becomes less valuable. The EPS product increases the ability of a college admissions leader -- working with College Board staff or an EM consultant -- to plan recruiting efforts centrally. -->

A second reason that Geomarkets may explain recuriting visits is because Geomarkets became an organizing principle for how admissions offices allocate admissions recruiters to territories. This process exemplifies performativity, whereby Geomarkets were created to mirror the territories of admissions officers and, subsequently, admissions offices structured recruiting territories around Geomarkets. Geomarkets became part of the shorthand lexicon of the National Association of College Admissions Officers (NACAC). On background, admissions officers and enrollment consultants told us it remains common parlance for admissions officers to introduce themselves to one another by saying something like, "I recruit 'PA 2'," which refers to the "Chester County, PA Geomarket." In states a college recruits heavily from, admissions officers may be assigned specific Geomarkets as their territory. This can be seen in the Chicago-land recruiting territories of University of Chicago in \@fig-chicago-recruiting. [ONE OR TWO SENTENCES ABOUT DATA ON GEOMARKETS AND RECRUITING TERRITORIES].
<!--should you say that more affluent, but less populated geomarkets may get their own admissions recruiter?-->

Our second research question is, to what extent are visit patterns consistent with recommendations from the Market Segment Model? For selective private -- and most public -- institutions in our sample, the Market Segment Model recommends visiting affluent Geomarkets in geographic regions where many students are likely to consider a college like yours. 

Organizations depend on a stable flow of critical resources [@RN959] and the Market Segment Model is an algorithm for identifying the location of desirable patrons [@RN4517], those willing to pay private/nonresident tuition price. Drawing from @RN5072, the US postsecondary education system is highly ordinal and so are student market segments. Selective private colleges primarily depend on students from the regional and national market segments. @RN4982 shows that regional and national students tend to come from affluent, college-educated households. These affluent households are not scattered randomly across the country; they clump together in particular geographic communities. Like UK "league tables" [@RN5005], Geomarkets are a means of commensurating geographically disparate localities in terms of the number of students from each market segment. Imagine that the University of Arkansas wants to find new markets and has strong regional, but not national demand. The Market Segment Model might suggest that the university should consider the affluent "TX 23 -- Collin & Rockwall" (near Dallas) and the "TX 15 -- Northwest Houston & Conroe School District" Geomarkets, which contain large numbers of regional and national students, but not the poorer "TX 19 -- City of Dallas" or "TX 17 -- City of Houston (East)," which contain relatively few regional and national students. 


<!-- CUT TEXT RESTATING GENERAL STATEMENTS ABOUT THEORY CUZ YOU STATED THIS ABOVE AND WE ARE SHORT ON SPACE
Concepts from resource dependence theory, commensuration, and ordinalization help us unpack these recommendations. The most basic precept of RDT is that all organizations require resources from the external environment to survive. @RN4517 highlight the centrality of patrons in the development of US higher education. Across the "associational" and "market" configurations, selective private colleges have depended on patronage from businesses, congregations, and wealthy households. The intervening "national service" configuration paved the the current market configuration by creating a national voucher system -- Title IV federal financial aid -- in which household savings and federal financial aid follows students to whichever institution they decide to attend. 

Williams College enjoys student demand across the nation, but only from households willing to travel that far for college. Therefore, it wouldn't make sense to recruit in a Geomarket in Indiana that contains few students from the national market segment. 

THE LOGIC HERE DIDN'T FEEL QUITE RIGHT; AND WE ARE SHORT ON SPACE
Let us imagine that Marquette primarily depends on student demand from the Midwest region. The Market Segment Model suggests that they should recruit from Geomarkets with a large number of regional students. However, Marquette should be wary of affluent Geomarkets outside of the midwest if EPS software indicates that students from these Geomarkets are unwilling to consider Marquette. -->

We predict that most colleges in our sample will adhere to a regional or national (but not an in-state) recruiting strategy depending on whether they have regional or national enrollment demand. We predict that colleges will disproportionately visit high schools located in affluent Geomarkets. We posit two performativity rationale for these predictions. First, admissions offices may allocate more admissions officers to affluent Geomarkets, relative the number of students in those Geomarkets. For example, the University of Chicago assigns one recruiter to the "IL 9 - North Shore" Geomarket, which had a 2020 population of about 161,000 and one recruiter to the "IL 12 - South and Southwest Suburbs" Geomarket, which had a 2020 population of about 1.2 million.  Second, similar to the Black-Scholes model being written into spreadhseets used by options traders [@RN5067], EPS software encourages colleges to implement a recruiting strategy consistent with the Market Segment Model -- "focus your valuable time and resources on the right prospects" [@RN5019] -- because the logic of the Market Segment Model is embedded within the software.

<!-- YOU PUT THIS TEXT ABOVE


On background, EPS software often recommended visiting the same sets of affluent, high-achieving high schools that were receiving visits from other colleges. We were told that savvier, quantitatively-adept admissions offices used EPS to visit schools that EPS recommended ignoring because there would be less competition for the good students who attended these high schools.  
RQ3 asks, to what extent does Geomarket popularity (Z) -- measured as the number of visits per school -- mediate the relationship between school composition (X) and the probability of a receiving a visit (Y)?
-->

RQ3 asks, to what extent does Geomarket popularity -- measured as the number of visits per school -- mediate the relationship between school composition and the probability of a receiving a visit? Previous research shows that having a high proportion of free-reduced lunch students or Black/Hispanic students is negatively associated with receiving a visit [@RN4758]. Therefore, RQ3 investigates whether high-SES versus low-SES schools (and low versus high share of Black/Hispanic enrollment) benefit more from being located in a popular Geomarket. We hypothesize that high-SES and low Black/Hispanic enrollment schools benefit more from being located in a popular Geomarket. Our rationale draws from @RN4808, who highlight the role of "good matches" between ordinally classified products and ordinally classified customers. @RN5072[pp. 20-21] offers an anecdote: 

> One of the authors had a credit card transaction denied while trying to refill her car’s gas tank in a high-poverty Oakland neighborhood. The clerk indicated with resigned anger that the location of his gas station was the likely cause of the problem. Back in Berkeley a few minutes later, the card worked without a hitch. 

Not coincidentally, Oakland is in Geomarket "CA 7 -- City of Oakland" whereas Berkeley is in Geomarket "CA 8 -- Alameda County excluding Oakland." @RN4808[p. 17] write that "‘good matches’ are perceived as natural because they fit well with how things already are." An affluent school in an affluent Geomarket is a good match because it exemplifies the schools we expect to find. We predict that such schools benefit by receiving more visits than an affluent school in a less affluent Geomarket. By contrast, a poor school or a predominantly Black/Hispanic school in an affluent Geomarket is not a good match and we predict that these schools will not reap the same locational benefits.

# References

\singlespacing
\begingroup
\small


::: {#refs}
:::

<!-- TABLES 
\endgroup
\clearpage
\singlespacing
-->