---
#title: "The Road Not Taken: College Board Geomarkets and Recruiting Visits by Selective Colleges"
#title: "Performing Social Closure: College Board Geomarkets and Recruiting Visits by Selective Colleges"
#title: "Recruiting as Performance: College Board Geomarkets and High School Visits by Selective Colleges"
#title: "Recruiting as Performativity: "
title: "Performing College Recruiting: College Board Geomarkets and High School Visits by Selective Colleges"
#title: "The Performance of Recruiting: College Board Geomarkets and High School Visits by Selective Colleges"
#title: "Performativity in College Recruiting: College Board Geomarkets and High School Visits by Selective Colleges"

# author: ["Ozan Jaquette (UCLA)", "Karina Salazar (University of Arizona)", "Crystal Han (Stanford University)"]
bibliography: ./../../cb_geo/assets/bib/cb_geomarket_bib.bib
csl: ./../../cb_geo/assets/bib/chicago-author-date.csl
format:
  #docx:
  pdf:
    documentclass: article
    #papersize: letter
    number-sections: true
    number-depth: 2
    #toc: FALSE
    #pandoc_args: !expr rmdfiltr::add_wordcount_filter(rmdfiltr::add_citeproc_filter(args = NULL))
    #keep_tex: true
editor: visual
geometry:
  - margin=1in
fontsize: 11pt
header-includes:
  - \usepackage{setspace}
  - \doublespacing
---

```{r setup, include=FALSE}
library(knitr)
#library(bookdown)

# https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_pdf.pdf
library(kableExtra)

#hey ho This many words: {{< words-total >}}
```

\pagenumbering{roman}
\newpage

**ABSTRACT**

Sociology of education investigates consumer-facing intermediaries (e.g., college rankings), but pays less attention to business-facing intermediaries that classify students on behalf of schools/colleges. The market devices literature offers useful concepts. Market devices are calculative tools incorporated into products or economic transactions. Performativity is the idea that actors utilize market devices in ways that enact behavior consistent with economic theories. College Board Geomarkets and the Market Segment model are market devices for higher education recruiting. Geomarkets carve metropolitan areas into smaller geographic units meant to define local recruiting markets. The Market Segment model predicts how student demand for a college varies by Geomarket as a function of social class. These market devices were the basis for the College Board Enrollment Planning Service, an early software-as-a-service product that helped colleges plan recruiting. Using data on recruiting visits to high schools made in 2017 by a sample of 42 colleges, we examine whether the relationship between recruiting visits and Geomarkets is consistent with theoretical expectations about performativity.

\newpage
\pagenumbering{gobble}
\pagenumbering{arabic}

# Introduction

Overarching RQ

-   What is the relationship between College Board Geomarkets (X) and high school recruiting visit patterns?

Concrete RQs

-   To what extent do college board Geomarkets explain which high schools receive recruiting visits from public research and selective private PSIs?
-   To what extent are visit patterns consistent with recommendations from the Market Segment?
-   If and to what extent does geomarket popularity \[Z\] mediate the relationship between school composition \[free reduced lunch; share Black/Hispanic\] and probability of a high school getting a visit \[Y\]?

```{=html}
<!--
Maybe the intro is about how scholarship on college access thinks about college preferences/practicies being primarily a function of stuff like rankings or other widely known institutional logics like holistic admissions but ignoring third-party market devices in the realm of market resarch. [this is the debate in the ivory tower type hook]
-->
```

# Dependence and Patronage in the Enrollment Economy

The "enrollment economy" refers to reliance on student enrollment for financial stability. The concept was introduced by @RN2401 \[p. 332\], in his analysis of California adult education institutions: "The most important pressures on these schools in their day-to-day administration arise from the *enrollment economy* \ldots Financial support from the state is figured by the hours of attendance logged the previous year \ldots and a major slump in attendance constitutes a serious threat to organizational welfare." (p. 332). At the opposite end of the prestige spectrum, @RN1549 [p. 17] describes dependence on students by selective private colleges: "the technology of producing much of what is sold in higher education is unusual in that colleges can buy important inputs to their production only from the customers who buy their products; that is, higher education uses a customer-input technology. Colleges depend on enrolled students for tuition revenue and on alumni for donation revenue. They depend on enrolled students for peer learning effects. Furthermore, the characteristics of enrolled students -- for example, average SAT scores -- substantially determine their national ranking, which then determines student demand for the subsequent cohort of prospects \[CITE\] and also affects research funding and donation revenue \[CITE\].

```{=html}
<!-- FULL CLARK QUOTE 
> The most important pressures on these schools in their day-to-day administration arise from the *enrollment economy* \ldots Financial support from the state is figured by the hours of attendance logged the previous year, producing a direct relation between student turnout and level and level of state aid. Unless a school maintains and preferably increases attendance, future support is likely to stagnate, and a major slump in attendance constitutes a serious threat to organizational welfare." (p. 332). 
-->
```

@RN4517 place the enrollment economy in historical context by tracing the sources of patronage accross three "institutional configurations" -- associational, national service, and market -- that reflect major epochs in U.S. higher education.[^1] The national service configuration, beginning after World War II, refers to massive federal and state investment in higher education as an engine of American political and technological development. Examples include federal research funding, state appropriations, and federal financial aid. The market configuration is associated with contemporary state disinvestment in public higher education, coupled with federal legislation encouraging research commercialization. Patronage -- the adage, 'he who pays the piper, calls the tune' -- is a central theme across all configurations. In the national service configuration, federal and state governments are the primary patrons. For example, in the analysis of California adult education by @RN2401, state revenue is tied to student enrollment, not student ability to pay. In the market configuration, the primary patrons are households and private sector organizations. Here, the enrollment economy depends on identifying prospective students with high ability to pay.

[^1]: Early U.S. colleges were "associational" because were initiated by religious or business associations and because colleges knit "themselves together in a wide variety of interorganizational associations" [@RN4517, p. 126] to solve common problems. Examples include voluntary accreditation, professional associations, and member associations like the Consortium on Financing Financing Higher Education (COFHE).

```{=html}
<!-- PARAGRAPH SKETCHING ENROLLMENT ECONOMY FOR SAMPLE
We sketch the enrollment economy for our analysis sample, consisting of 12 selective private liberal arts colleges, 14 selective private research universities, and 16 public research universities. The enrollment economy for selective liberal arts colleges hews most closely to the characterization of @RN1549; their position in the zero-sum game for prestige substantially depends on the high school achievement of enrolled students and the primary revenue sources are tuition and donations from wealthy alumni.^[Home equity lines of credit and increases in federal student loan maximums facilitated long-term growth in tuition prices and an arms race in spending on education quality and amenities [@RN4461; @RN5066].] Selective liberal arts colleges primarily enroll rich students with a modicum of students from middle- and lower-class backgrounds [@RN4722]. Only a handful of colleges (e.g., Williams) enjoy strong demand from students who are both affluent and high achieving. Outside the top ten or so, the priority becomes "affluent families \[who\] could absorb the College's full tuition and boar costs with little, if any, financial aid" [@RN3519, p. 73; @RN3522]. Selective private research universities face a similar enrollment economy as liberal arts colleges, but are less dependent on students to the extent that they derive financial and reputional resources from faculty research. Historically, public research universities were less beholden to the enrollment economy due to federal research funding and state appropriations that were loosely coupled to enrollment. State appropriations became increasingly volatile from the 1980s through the 2000s [@RN2271], declining substantially during economic downturns, but failing to rebound during periods of recovery [@RN2271]. Given price ceilings on resident tuition, public flagship universities responded by pursing nonresident enrollment as a substitute for state appropriations [@RN3753].[^1] Nonresident students tend to be more affluent than resident students [@RN3685]. Therefore, state disinvestment makes public research universities beholden to the enrollment economy that governs selective private research universities, pursuing national recognition rankings and/or intercollegiate athletics as a means of generating demand from affluent households willing to pay the higher price of nonresident tuition. 

[^1]: From 2002-03 to 2012-13, a 10% decline in state appropriations was associated with a 4.6% increase in subsequent nonresident freshman enrollment @RN3753
-->
```

```{=html}
<!-- 
Scholarship at the nexus of EM and college access can be categorized by which part(s) of the enrollment funnel it speaks to. The enrollment funnel -- shown in Figure @fig-em-funnel and based on the traditional marketing funnel -- is a conceptual model used by the EM industry to depict stages in the process of recruiting students [@RN4986; @RN2004]. The funnel begins with a large pool of "prospects" (the universe of prospective students the college would like to enroll), followed by "leads" (prospects whose contact information has been obtained), "inquiries" (prospects who contact the institution), "applicants," "admits," and "enrolled students." The funnel narrows at each successive stage in order to convey the assumption of "melt" (e.g., a subset of "inquiries" will apply). The purpose of the enrollment funnel is to inform recruiting interventions that target one or more stages. These interventions seek to increase the probability of "conversion" across stages [@RN4322]. In sociology, economics, and related interdisciplinary fields, the majority of scholarship focuses on the admissions stage -- for example, analyzing which admissions criteria are utilized and/or which applicants are admitted [e.g., @RN4874; @RN4993; @RN4131; @RN3522] -- or on financial aid leveraging as a means to convert admits to enrolled students [e.g., @RN3133; @RN3762]. For example, @RN2241 shows that from 1992 to 2003, the amount of institutional financial aid awarded on behalf of student financial need decreased relative to financial aid awarded to student academic achievement.
-->
```

For colleges in the enrollment economy, organizational stability is the responsibility of enrollment management (EM). As a profession, EM integrates techniques from marketing and economics in order to "influence the characteristics and the size of enrolled student bodies" [@RN2771, p. xiv]. As an administrative structure, the "office of enrollment management" typically controls and coordinate the functional activities of admissions, financial aid, and recruiting [@RN2406; @RN3625]. The administrative structure of EM offers one means of categorizing scholarship about the supply-side of college access. In sociology, economics, and related interdisciplinary fields, the majority of scholarship focuses on admissions [e.g., @RN4874; @RN4993; @RN4131; @RN3522] or on financial aid [e.g., @RN3133; @RN3762]. A growing literature in sociology analyzes the earlier "recruiting" stages of acquiring "leads," and soliciting "inquiries" and applications \[CITE\]. Several monographs analyze recruiting as part of broader studies on enrollment management [@RN3519], high school to college transitions [@RN4324], elite reproduction [@RN4407], or political economy [@cottom2017lower]. We situate the present manuscript within scholarship on recruiting that focuses on linkages between colleges and high schools [e.g., @RN4324; @RN3519; @RN4321].

The relationship between colleges and high schools is characterized by mutual -- but often asymmetric -- dependence. Colleges depend on a stable flow of high school students who collectively satisfy broad enrollment goals [@RN2772] -- related to revenue, academic profile, and diversity -- and the granular demands of internal constituents [@RN3519] -- for example, the biology department needs majors and the band needs players. Although a college does not depend on any single high school to provide a substantial share of enrollment, the list of schools that enroll desirable students who are interested in attending is finite, thereby motivating "the recruiters' emphasis on feeder high schools" [@RN4982, p. 11]. High schools want to send their students to college. This goal is particularly important at expensive private schools and affluent public high schools, where placement into selective colleges functions as a key justification for both high tuition and high local housing prices. Dyadic relationships are seldom symmetric [@RN960]. A college values a high school to the extent that they want to enroll students from that high school. A private college that depends mostly on tuition revenue may place minimal value on a high school that primarily enrolls low-income students. A high school values a college to the extent that they want some of their students to enroll in that college. The distribution of student achievement suggests that high schools value a range of colleges. Colleges below this range may be viewed with disdain while colleges above this range may be viewed as unattainable.

```{=html}
<!-- 
@RN959 describe inter-organizational linkages as a tool for managing dependence on resource providers that the organization cannot acquire or substitute. Whereas professional associations (e.g., American Council on Education) create links between direct competitors beholden to a common resource provider (often the government), cooptation is the strategy of an organization establishing relationships with particular resource providers in order to socialize the resource provider to the goals of the organizaton. Drawing from @RN3519 and @RN4321, the relationship between college admissions officers and high school guidance counselors is one of mutual cooptation. The admissions officer tries to convince the guidance counselor of the special mission/character of the college, hoping the guidance counselor steers students to the college. The guidance counselor tries to convince the college admissions officer of the special value of the school's students, especially students deemed marginal by conventional measures of academic achievement [@RN4321].[^2]

[^2]: @RN4321 describes how high school guidance counselors at elite private schools exploit the enrollment goals of selective colleges in order to "get comparatively under-qualified students into top colleges and universities" (p. 98). Admissions officers at selective colleges want to know whether an applicant would enroll if granted admission because admissions and yield rates are inputs of USNWR rankings. This desire for credible information creates an opportunity for high school counselors to advocate on behalf of their students. Guidance counselors tell admissions counselors which highly-sought-after applicants are likely to decline an offer, while lobbying for an applicant who has relatively weak academic credentials but is sure to matriculate and has "character" and extracurricular activities demanded by internal constituents of the college.
-->
```

@RN3519 provides an ethnography of enrollment management at a selective private liberal arts college. Being tuition-dependent and sensitive about its position in the rankings, The College focuses on enrollment goals related to academic profile and revenue generation. @RN3519 highlights the relational function of off-campus recruiting visits: "the College's reputation and the quality of its applicant pool are dependent upon its connections with high schools nationwide" (p. 54). During the autumn "travel season," admissions officers visit selected high schools across the country "to spread word of the institution and maintain relationships with guidance counselors" (p. 53-54). @RN4741 reported that "calling high school counselors after visits" was an effective and widely-used outreach strategy for both private universities and public universities. Thus, relationship maintenance remains a high-touch process even in the digital age. The College tended to visit the same "feeder" schools year after year because recruiting depends on long-term relationships. Visited schools tend to be affluent schools -- in particular, private schools -- that possess the resources to host a visit and enroll high-achieving students who can afford tuition.

Whereas scholars in the sociology of education have investigated recruiting as part of a broader analysis, AUTHORS [-@RN4758; -@RN4759; -@RN5023] have attempted to develop a literature that makes college recruiting behavior the object of empirical analysis. @RN4758 argue that off-campus recruiting visits are a credible indicator of college enrollment priorities because recruiting visits cost resources and because visits to individual schools are largely invisible to macro stakeholders.[^2] @RN4758 analyzed recruiting visits made by public research universities. The authors found that 12 of the 15 universities made more visits to out-of-state schools than in-state schools. These out-of-state visits focused on affluent, predominantly white public high schools. Set against scholarship about nonresident enrollment growth as a response to declining state support [@RN3753; @RN3685], these results suggest that many public research universities prioritize enrollment from wealthy out-of-state students. <!-- 
Many colleges list their "travel schedule" on their admissions page. As described below, @RN4449 collected data about off-campus recruiting visits made during the 2017 calendar year from a (non-random) sample of public research universities, selective private research universities, and selective private liberal arts colleges by scraping these data from their admissions pages.
-->

[^2]: Sociological theories of organizational behavior argue that organizations expend substantial resources on goals they care about while symbolically adopting -- highly visible, ceremonial behavior with few resources expending -- goals demanded by stakeholders in the broader institutional environment.

@RN5023 conduct a social network analysis of recruiting visits to private high schools by a sample of public research universities and selective private research universities. They conceptualize visits as an indicator of a social relationship between a college and a high school, indicating that the college wants to enroll some students from the high school and that the high school wants to send some students to that college. Universities in the sample made a disproportionately large number of visits to private high schools relative to public high schools. Analyses revealed substantial overlap in the direct recruiting networks of public and private universities. @RN4759 conducted geospatial analyses of out-of-state recruiting visits to Los Angeles and Dallas by four public research universities. She found that universities engage in "recruitment redlining -- the circuitous avoidance of predominantly Black and Latinx communities along recruiting visit paths" (p. 585).

We argue that scholarship on enrollment management has gone astray by focusing on college behavior as the source of racial and socioeconomic inequality in college access. Empirically, this literature focuses on the behavior of individual colleges. In turn, the literature assumes that enrollment management behavior is a function of individual college preferences, which are conditioned by logics and forces in the organizational field (e.g., rankings, state funding). \[DELETED BELOW SENTENCE ON KRIPPNER HERE\] To our knowledge, scholarship on enrollment management has failed to consider third-party intermediaries that classify students on behalf of colleges. We present the case of Geomarkets and the Market Segment Model. <!-- 
@RN5070 makes a similar observation about the sociology of gender in her analysis of insurance products, stating that feminist scholars considered gender discrimination an "organizational matter -- a product of administrative routines such as hiring procedures, promotion protocols \ldots \[but\] this approach reinforced the notion that markets do not themselves contribute to discriminatory outcomes." 

We present the case of Geomarkets and The Market Segment Model, which classified students and localities on behalf of colleges looking for customers.-->

# Geomarkets and the Market Segment Model

```{=html}
<!-- 
We describe the case of Geomarkets and the Market Segment Model, adding deeper context as we introduce concepts from market devices, commensuration, and ordinal classification. -->
```

Geomarkets were conceived in the late 1970s, when colleges were concerned about declining demographics. @RN4982 \[p. ix\] write that demographer "Stephen @RN5076 had already frightened everyone who would listen with his projection of 40-percent declines in college enrollments by the close of the 1980s." Elite colleges responded by leaning on the associational configuration [@RN4517] to solve problems common to the group. The project began when UPenn president, Martin Meyerson, tasked UPenn professor Robert Zemsky, to figure out, "'Who thinks about Penn?'" and "'What other institutions do they think about when they think about us?'" [@RN4982, p. x]:

> "In pursuit of these questions, we began working in 1978 with the Market Research Committee of the Consortium on Financing Financing Higher Education (COFHE). The Consortium, a group of thirty selective private institutions, had in its brief history developed a remarkable tradition of sharing data\ldots For nearly a year, the Consortium's Market Research Committee provided focus to our efforts. Much of this project's framework -- the Market Segment Model and its derivation from admissions officers' folklore was shaped and then reshaped in our discussions with members of the committee."

```{=html}
<!-- FULL QUOTE
> "In pursuit of these questions, we began working in 1978 with the Market Research Committee of the Consortium on Financing Financing Higher Education (COFHE). The Consortium, a group of thirty selective private institutions, had in its brief history developed a remarkable tradition of sharing data. Members of COFHE had come to know almost as much about one another's applicant pools as they did about their own. For nearly a year, the Consortium's Market Research Committee provided focus to our efforts. Much of this project's framework -- the Market Segment Model and its derivation from admissions officers' folklore was shaped and then reshaped in our discussions with members of the committee."
-->
```

@RN4982 conceived of the Market Segment Model as an effort to "capture and quantify" (p. 11) the knowledge of admissions officers: "We believe that the intuitions of admissions officers actually comprise a remarkably systematic body of knowledge about the college selection process\ldots Our research is based upon listening carefully to what admissions officers have to say (pp. 9-10). The "initial \[analytic\] task" was to define geographic boundaries "in a manner consistent with admissions officers' intuitive understanding of student pools" [@RN4982, p. 4]. Quoting an admissions officer, @RN4982 \[p. 11\] write, "'There are only three kinds of college-bound students: those who want to live at home, those who want to live on campus but bring their laundry home, and those who want to go far enough from home that Mom and Dad can't visit without calling first.'" As such, @RN4982 [p. 11] created "three types of boundaries -- region, state, and community." The initial regions in the project were New England, Middle States, and the South. Next, they "divided each state into as few as two and as many as thirty community-based enrollment markets or pools, for a total of 143 separate markets" (p. 11). These enrollment markets, later called Geomarkets, were intended to be consistent with the conception of a catchment market from the perspective of admissions counselors. @RN4982 [pp. 11-12] described the creation of Geomarket borders only briefly:

> In many cases, the market boundaries match formal political and educational divisions, reflecting natural channels of communication. Each major metropolitan area is composed of several markets, usually corresponding to the inner city, a first ring of suburbs, and an outer ring of suburbs. In more sparsely populated areas, communities are sometimes combined in order to make the analysis meaningful.

Over time, the project goal morphed into predicting student demand for any college from any locality. However, "to gain a truly comprehensive view of the collegiate enrollment market, we needed a database that described most institutions and most students" [@RN4982, p. x]. The group approached College Board. "Coincidentally, the Board was reviewing its own efforts to help colleges estimate their enrollment potential" [@RN4982, p. x]. College Board provided score-sending data for all 1980 SAT test-takers. For a given student, each college that receives a score from the student can be defined as "local" (college located in the the same Geomarket as the student), "in-state" (same state but different Geomarket), "regional" (same region but different state), or "national" (different region). @RN4982 classified each SAT test-taker into one of four student *market segments*. A student is categorized in the "local" market segment if they submit more SAT scores to local institutions than they do to in-state, regional, or national institutions. An "in-state" student submits more SAT scores to in-state institutions than they do to local, regional, or national institutions, etc. The Market Segment Model "was nothing more than a set of simple rules for disaggregating high school seniors into similar groups" [@RN4982, p. 4]. "The model worked because students, once so disaggregated, appeared to behave in remarkably consistent ways."

@RN4982 [Chapter 3] investigates which student characteristics predict whether a student belongs to the local, in-state, regional, or national market segment. The analyses identify four variables -- educational aspirations, parental education, scholastic aptitude, and family income -- that predict score-sending behavior, both individually and in combination. The resulting thesis is that student demand for college is a function of social origin. These four variables "reflect the basic social patterns of the nation; it would have been surprising if these were not the four social variables that best explained the patterns of college choice" [@RN4982, p. 33]. The analyses conclude (p. 42) that "our research has simply demonstrated what everyone has always known: communities with high levels of family income and parental education are also communities in which students have higher than average SATs and more far-reaching aspirations."

However, Geomarkets differ in the relative abundance of students with particular socioeconomic characteristics. As college leaders sought new sources of patronage, the Market Segment Model yielded practical implications about which communities to target. @RN4982 [p. 44] recommend that colleges target Geomarkets with desirable compositions of socioeconomic characteristics in order to reach students from desired student market segments:

> On occasion, senior spokespersons for the profession worry that students outside the main \[Geo\]market areas remain forgotten and hence, unchallenged. Inevitably, the increasing competition for students, the expense of travel and mailings, and internal political constraints compel institutions to concentrate their efforts where they will do the most good. The result is a natural reinforcing of the basic socioeconomic patterns that gave shape in the first place to the structure of college choice.

@RN4982 developed two analytic outputs, (1) the Market Segment Profile and (2) the Institutional Profile. The Market Segment profile showed -- separately by Geomarket -- the number of students from each market segment (local, in-state, regional, national), their socioeconomic characteristics, and average test scores. The Institutional Profile showed -- separately by Geomarket and institution (your own or a competitor) -- how many students from each market segment sent scores to that institution.

In 1984, College Board transformed the Market Segment Model and associated outputs into the Enrollment Planning Service (EPS), an early software-as-service platform sold to colleges that was based on @RN4982. For any Geomarket, colleges could obtain the Market Segment Report and the Institutional Profile for themselves or a competitor. Based on background conversations with EM professionals, EPS software also provided information about the score-sending behavior of individual high schools within each Geomarket. Typical @RN5019 marketing material describes EPS as, "the marketing software that pinpoints the schools and Geomarkets where your best prospects are most likely to be found. With the click of a mouse, EPS provides you with comprehensive reports on your markets, your position in those markets, and your competition." Following @RN4982, the EPS platform encouraged users to, first, identify promising Geomarkets and, second, to identify desirable high schools for recruiting visits. To find new markets, EPS encouraged colleges to select peer colleges and identify Geomarkets where a large number of students sent scores to those colleges. Market research suggests that EPS was highly salient. @RN5021 reports that in 1995, 37% of 4-year publics and 49% of 4-year privates used EPS, while 41% of 4-year publics and 16% of 4-year privates used ACT's market analysis service product.

```{=html}
<!-- CUT TEXT

Therefore, colleges used EPS software to decide which Geomarkets to recruit from and which high schools to visit within targeted Geomarkets. 

Quantification has consequences to the extent that the stakeholders care about the numbers [@RN5006]. 
-->
```

# Theory: Devices, Commensuration, and Classification

*Market devices*. We conceive of Geomarkets, the Market Segment Model, and the subsequent Enrollment Planning Service product as examples of "market devices" [@RN5064; @RN5067]. Market devices are discreet calculative tools (e.g., algorithms, metrics, graphs, screens, rankings models, spreadsheets) that are incorporated into products or economic transactions. In this framework, neither market devices nor actors have agency in isolation from one another. "Agencements" are actions that become possible when actors utilize market devices. To make these concepts concrete, consider the case of US News College Rankings. The market device is the ranking tool itself -- which consists of data inputs, an algorithm, and a ranked list published on a website. Agencements refer to the ways that actors utilize the rankings market device. For example, prospective students incorporate rankings in their college search process, employers use rankings to decide which colleges they will recruit from, and college administrators make resource allocation decisions designed to move up in the rankings [@RN5003].

```{=html}
<!-- OG FIRST PARAGRAPH
Core concepts in the market devices literature are market devices, agencement, and performativity. 
Market devices are the assemblage of techniques, theories, and culture that make economic action possible [@callon1998embeddedness]. Drawing from Krippner’s [-@RN5070] study of insurance, an example of a market device is the statistical models that assign individuals to "risk pools" for insurance products. Market devices shift scholarly attention to the individual components -- including techniques, theories, cultural logics, and histories -- that are foundational to products and to markets [@RN5071] The analysis of market devices in insurance also includes the long history of mutualism that the insurance industry emerges from. Market devices are also useful because they shift source of social inequality from organizations to markets. @RN5070 argues that the statistical models underlying insurance products are "gendered market devices" because gender is one of the variables used to assign people to different risk pools. -->
```

"Performativity" describes the consequences of market devices. Performativity is the idea that economic theories do not merely describe behavior, rather market devices are constructed and acted upon in ways the bring about behavior consistent with the theory [@RN5064; @RN5067].[^3] For example, @RN5067 provide a historical sociology of the Chicago Board Options Exchange, which opened in 1973. An option is a contract that gives the holder the right to buy or sell an asset (e.g., a stock) at a given price. Economists Fischer Black and Myron Scholes developed the Black-Scholes model -- a calculative market device -- to predict the price of options @RN5074, eventually winning the Nobel Prize in Economics. Initially, the Black-Scholes algorithm did not accurately predict the price of options. Black-Scholes model predictions became more accurate over time because options traders began embedding the logic and components of the model into spreadsheets/software. That is, the models predictions became more accurate because the model produced the prices it predicted [@RN5067]! @RN1776 provide an example of performativity for the case of US News College Rankings. The reputational assessment of senior administrators was a substantial component of the rankings algorithm. @RN1776 show that administrators based their assessment scores on the prior overall rankings. Therefore, the rankings algorithm disciplines administrators to provide assessments that are consistent with the prior rankings.

[^3]: Performativity is related to core concepts from the quantification literature, which has utilized college rankings as a case [@RN5003]. We highlight reactivity (people and orginizations change behavior in response to salient quantitative measures), discipline (quantification disciplines actors to react in particular ways), and authority (quantification often weakens discretion of local decision-makers). <!-- 
    Three effects quantification are reactivity (people and orginizations change behavior in response to salient quantitative measures), discipline (quantification disciplines actors to react in particular ways), and authority (quantification often weakens discretion of local decision-makers) [@RN5007]. The canonical case is USNWR law school rankings [@RN5003; @RN2356; @RN2376; @RN2375], which were developed as a mechanism to inform students about the prospective students about the relative quality of different programs. Rankings had the intended consequence of affecting (reactivity) where students apply and enroll [@RN5003]. Rankings also affected hiring decisions of firms because clients evaluated firms based on the prestige of law schools attended by firm lawyers. Once law schools realized that important constituents "used rankings to make decisions that had large consequences for schools" [@RN5007, p. 415], rankings disciplined the behavior of law schools. For example, characteristics valued by the rankings system (e.g., LSAT scores) became more important for decisions about admissions and merit aid. Rankings also weakened the *authority* of admissions personnel to make independent decisions about class size and which applicants to admit [@RN5003].
    -->

```{=html}
<!-- CUT TEXT ON CULTURE AND CREATION OF MARKET DEVICES

Analyzing the 1970s origins of Chicago's financial derivatives market, @RN5067 observed that the creation of new market devices requires collective action amongst interconnected members with shared goals and shared cultural understandings, those "classic themes of economic socoiology" (p. 109). Market devices often carry the culture of status groups that create them [@RN5070; @RN5071]. @RN3547 shows how the Protestant upper class status group that controlled Ivy League colleges in the early 20th Century achieved social closure by developing "character" admissions criteria, a sort of market device that effectively excluded Jews. The Market Segment Model was created and supported by COFHE and College Board, membership associations led by upper-class white men with strong ties to elite private colleges. Unsurprisingly, @RN4982 argues that student demand for college is a function of social class and, in turn, social class is the organizing principle of competition between colleges:  SALIENT TEXT FROM PAGE 45 IF YOU WANT TO KEEP IT

Most admissions officers\ldots intuitively understand that students think not so much of individual institutions as of groups of institutions. In the words of one veteran dean of admissions, 'We are known primarily by the company we keep.' For this reason, colleges actually encourage competition wwith one another to define their places in the market. Members of the Consortium of Financing Higher Education (COFHE) -- a group of thirty highly selective, high-cost, private institutions -- regularly exchange detailed and confidential information about their applicant pools, admissions strategies, and financial aid programs. What every envious admissions officer outside the Consortium understands is that these thirty institutions are strengthened by their collectivity, though they are in fact one another's principal competitors.
-->
```

Although canonical contributions to the market devices literature did not focus on structural inequality -- race, gender, class, @RN4777 argue that market devices literature can offer novel insights about the mechanisms of structural inequality. @RN5070 offers an empirical illustration in her analysis of insurance products. @RN5070 [p. 598] observes that prior feminist organizational scholarship considers gender discrimination an "organizational matter -- a product of administrative routines such as hiring procedures, promotion protocols \ldots \[but\] this approach reinforced the notion that markets do not themselves contribute to discriminatory outcomes." Drawing on documents from lawsuits filed by the National Association for Women, @RN5070 provides a historical document analysis that centers on the statistical models used to create life and car insurance products. She describes these models as "gendered market devices" because gender is one of the input variables utilized to assign individuals to different "risk pools."

The market devices literature offers great utility for the sociology of education subfield. The market devices literature examines how techniques, theories, culture, and agency interract in ways that make economic action possible [@RN4777; @RN5087]. Market devices are built upon other market devices and products are market devices that are composed of many market devices. This perspective legitimizes scholarly attention to individual components that are foundational to products and to markets [@RN5071], facilitating scholarship that sacrifices breadth for depth. For example, rather than analyzing insurance products as a whole, @RN5070 focuses on the statistical models that assign people to different risk pools. Moreover, the market devices literature legitimizes scholarly attention to the technical details of how market devices are constructed because technical details have consequences [@RN5067; @RN5078]. The flexibility of scope offered by the market devices literature is poignant for the sociology of education as third-party products increasingly perform core functions on behalf of schools and colleges. For scholarship that traces how a set of theories or techniques become embedded in one or more products, the market devices literature answers the essential question, ‘my study is a case of what?’ The market devices literature is situated within the economic sociology subfield. After some debate \[CITE\], it became part of the orthodoxy. Sociology of education draws heavily from organizational sociology [@RN5097] but less so from economic sociology and, to our knowledge, has not substantively utilized the market devices literature as a foundation for empirical scholarship.

We conceive of College Board Geomarkets and the Market Segment Model as market devices that are based on previous market devices and become inputs into subsequent market devices. The SAT is a market device that enables (agencement) colleges to compare students from different schools. An additional agencement is that students can send their SAT scores to colleges they are interested in. The Market Segment Model is a theory \[model? algorithm?\] of student demand that categorizes students into different market segments based on SAT score-sending behavior. Geomarkets are a market device that defines geographic localities and enables colleges to compares these localities based on the number of students from each market segment. Geomarkets are then incorporated into the Enrollment Planning Service product -- enabling colleges to decide which Geomarkets to recruit from and which high schools to visit [@RN4980] -- and the Student Search Service product -- enabling colleges to purchase the contact information of prospective students residing in desired Geomarkets. The high school visit patterns of colleges -- the object of empirical analysis in this manuscript -- speak to the performativity consequences of Geomarkets, the Market Segment Model, and EPS, whereby \ldots \[state what we expect to happe\]

**Comensuration**. The concept commensuration [@RN5071; @RN5063] helps us gain deeper insight about the agencement of market devices created by College Board. Commensuration is "the expression or measurement -- of characteristics normally represented by different units -- according to a common metric" [@RN5063, p. 315]. Commensuration is a process that requires work, akin to institutionalization. Once achieved, commensuration reduces the cognitive effort of decision-making. It is "a way to reduce and simplify disparate information into numbers that can easily be compared. This transformation allows people to quickly grasp, represent, and compare differences" (p. 316). For example, college rankings enable prospective students to compare colleges based on a single metric. Therefore, commensuration "can be understood as a system for discarding information and organizing what remains into new forms" [@RN5063, p. 317]. <!-- CUT TEXT

The process of commensuration identifies a quantitative metric that aids comparison, discarding the heterogenous collection of material that could be the basis of comparison. 
@RN5071 describes money as a tool of commensuration; an object that can be valued by money can be compared to any other object that can be valued by money.[^5] "Embedded in this logic is another assumption," @RN5063 [p. 324] that all value is relative and that the value of something can be expressed only in terms of its relation to something else." Things that cannot be expressed in terms of something else will not be valued. 
@RN5071 compares two famous oil spills, the Amoco Cadiz on the coast of Brittany, France and the Exxon Valdez in Alaska. The loss of fisheries could be valued using established theories of economic use. How should courts value the loss of nature? What is the economic value of nonuse? In the Amoco Cadiz case, courts ultimately decided that nature could not be valued. Environmental groups aided this decision, arguing that the environment is priceless and therefore incommensurate with money. "Incommensurables preclude trade-offs" write @RN5063[p. 326], "An incommensurable category encompasses things that are defined as socially unique in a specific way: they are not to be expressed in terms of some other category of value." In the Exxon Valdez case, plaintiffs drew from innovations in environmental economics, which had developed "nonuse damage valuation methods" [@RN5071, p. 1759]. This approach led to Exxon paying \$2 billion in civil charges, compared to \$0 paid by Amoco, even though the Amoco Cadiz spill was larger and in a more densely populated area. "Embedded in this logic [of commensuration] is another assumption," @RN5063[p. 324] that all value is relative and that the value of something can be expressed only in terms of its relation to something else. Things that cannot be expressed in terms of something else cannot be commensurated and will not be valued.

[^5]: @RN5071 compares two famous oil spill cases -- Amoco Cadiz on the coast of Brittany, France and the Exxon Valdez in Alaska -- valued "nonuse" damage to the environment. The Exxon Valdez relied on "nonuse damage valuation methods" and awarded huge settlements. The Amoco Cadiz case conceived of the envoronment as priceless and therefore incommensurate with money, resulting in no such monetary award.
-->

The analysis of UK school "league tables" by @RN5005 shows how commensuration can be a mechanism of social reproduction. In 1992, the UK government began publishing school league tables that ranked schools on student performance on national exams taken at age 16. League tables disciplined households -- and in turn schools -- to conceive of school quality in terms of test scores. League tables facilitated making evaluative comparisons between schools regardless of geographic proximity, but only in terms of the test score metric that was substantially a function of the class composition of schools. Following the adoption of league tables, localities with higher performing schools experienced growth in the share of managerial/professional households and a decline in the share of working-class households [@RN5005]. Therefore, league tables contributed to social reproduction because professional/managerial households were more aware of these consumer-facing metrics and had resources to respond by moving to more expensive neighbhorhoods, near higher performing schools. <!-- THIS IS THE CUT TRANSITION PARAGRAPH
Schools that performed well on initial league tables tended to be schools with a high share of professional/managerial families. Therefore, quantification takes a snapshot of existing social stratification and that snapshot becomes a power unto itself, amplifying the effect of previous strctural inequality on subsequent structural inequality.
-->

Economics conceives of the SAT as a market device that facilitates commensuration. @RN2247 argues that "information costs" were a barrier to the emergence of a national higher education market that efficiently matches students to colleges: "In 1955, there was no early national college aptitude test. Students and colleges simply did not know where students stood in the national distribution of high school graduates’ achievement or aptitude" (p. 103). Colleges could not make an apples-to-apples comparison between students from different schools because the information on a high school transcript "is relative to a standard that a college will not understand unless it draws very often from the high school" (p. 103). @RN2247 credits the SAT/ACT exams for the emergence of an efficient, national higher education market. Institutionalization of the SAT/ACT caused a "dramatic fall" in the cost of "colleges’ information about students" [@RN2247, p. 102].

```{=html}
<!-- CUT FOOTNOTE
[^6]: From 1955 to 1990, the number of colleges requiring the SAT/ACT increased dramatically from 143 to 1,839, while the number of SAT/ACT test-takers per freshman seat increased from 0.23 in 1955 to 0.87 in 2005.
-->
```

Geomarkets are a commensurating market device that builds on the SAT. @RN4982 created Geomarkets for the purpose of comparing different geographic recruiting territories. Consider the "MA10 -- Milton, Lexington, Waltham" Geomarket versus "NJ10 -- Bergen County." How should we compare them, by population density, household income, their history of segregation? @RN4982 developed the Market Segment Model, which created four student segments: "local" students, who primarily sent SAT scores to colleges in their home Geomarket; in-state students; regional students; and national students, who set SAT scores primarily to colleges outside their home region (e.g., New England). Whereas UK league tables allowed parents to compare geographically disparate schools based on test scores [@RN5005], the Market Segment Model enables enables colleges to compare geographically proximate and geographically disparate Geomarkets based on the number of students from each market segment. @RN4982 states that selective colleges primarily draw students from the regional and national market segments. The key to finding new student markets, then, is identifying Geomarkets with large numbers of regional and national students. This information could be obtained from College Board EPS software.

**Classification situations.** Finally, scholarship on ordinal classification situations [@RN4810; @RN5015; @RN4808; @RN5072] helps conceptualize how Geomarkets faciliate social and racial stratification in college access. @RN5072 defines three kinds of classification: *nominal* classifications, oriented to qualitative essense or "type" -- such as race, gender, country of citizenship, or biological taxonomies; *cardinal* classifications, oriented to quantities and magnitude (e.g., SAT score), where differences between quantities can be measured exactly but only for objects within the same nominal classification; and *ordinal* classifications, which are oriented to relative positions that can be hierarchically ranked, but the distance between positions are not measured quantitatively. @RN5072 describes the growing salience of ordinal classifications. Objects once considered incommensurate because they are different nominal categories become ranked values of a single ordinal classification. For example Niche national private school rankings -- utilized as a covariate in analyses below -- commensurate a heterogeneous population of schools via a single ordinal ranking. The college-for-all movement is associated with the nominal binary of a college student being replaced by more inclusive, but hierarchical, ordinal classifications that ranges from the part-time adult learner in a community college to full-time Ivy League students.

```{=html}
<!-- CUT SENTENCE
@RN5072 argues that the transformation from nominal to ordinal categories serves political liberalism because ordinal classifications are more inclusive. 
-->
```

```{=html}
<!--  CUT PARAGRAPHS -- DATA DRAGNETS
@RN4808 [p. 9] argue that contemporary organizations follow a "data imperative to collect as much data as possible." Historically, data were recorded manually by people writing in ledgers or by collecting survey data [@RN4808]. Contemporary "administrative data" are recorded automatically as a function of people engaging in transactions and being observed by devices. Data are collected with and without a use in mind, sold and resold to data aggregators, combined with other data sources, and incorporated into analyses that classify people and/or predict behavior [@RN4744; @RN4799; @RN5061].

The Market Segment Model offers an early example processes described by @RN4808. College Board collects data from students laboring on their platforms. Students manually record data by taking a test and by completing pretest survey questions (demographics, grades, social class, intended major). These data are repurposed into several products, for example *Student Search Service* and the *Admitted Student Questionnaire*. Students may send test scores to colleges they are interested in, a long-standing feature of the SAT product. Data on score-sending behavior are administrative data collected as a function of organizational operations. @RN4982 created the Market Segment Model based on 1980 score-sending data provided by College Board. -->
```

<!-- The ascendance of ordinal classifications yields ordinal interventions called "classification situations"-->

Classification situations are ordinal interventions whereby organizations "sort and slot people into new types of categories with different economic rewards or punishments attached to them" [@RN4810, p. 561]. Classification situations intervene on the concept of class. Historically, sociology defines social class from the production side of the economy (e.g., worker vs owner; clerical, manager, professional). By contrast, @RN4810 argue that processes of ordinalization "endogenous to the market" (p. 560) define class through effects on the *consumption* side of the economy. The canonical example is credit scores [@RN4877], which enable third-party intermediaries on supply side to "slice consumers into behaviorally-defined risk groups, and price offerings to them accordingly. On the demand side, consumers find themselves \ldots fitting into these categories -- which, by design, are not constructed from standard demographic classifications such as race" [@RN4810, p. 560] but are highly correlated with social categories. The goal of classification situations is "good matches," whereby an ordinal hierarchy of products match to an ordinal hierarchy of people. Businesses "seek good matches when they want to link a wealthy customer with a quality credit card, or a heavy drinker with a bad insurance plan" [@RN4808, p. 17]. Whereas economics tends to view such matches favorably -- for example, @RN2247 [p. 106] writes the "efficient outcome allocates students to colleges based on students’ ability to benefit from the \ldots magnitude of the human capital investment that the college offers" -- Sociology tends to highlight the predatory, extractive inclusion of formerly excluded consumers (e.g., for-profit colleges) [@RN4774].

```{=html}
<!-- PUT THIS BELOW INSTEAD
Classification situations intervene on the concept of class. Marx argues that class is defined by the production side of the economy, highlighting the binary of worker versus owner [@RN1423]. The social stratification literature introduce a spectrum of social class still largely defined by occupation (e.g., manager, professional) [e.g., @RN915], with the notable inclusion of educational attainment. 
[@RN4808, p. 17]:

> Companies seek good matches when they want to link a wealthy customer with a quality credit card, or a heavy drinker with a bad insurance plan. This kind of matching capitalizes on people’s differentiated dispositions and practical habits, what Pierre Bourdieu calls their habitus. The ‘good matches’ are perceived as natural because they fit well with how things already are.
-->
```

<!-- The Market Segment Model is a class- and geography-based theory of student demand that classifies consumers (prospective students) on behalf of consumers (colleges).  -->

Geomarkets and the Market Segment Model function together as ordinal market devices that match a socioeconomic hierarchy of places to a socioeconomic hierarchy of colleges.[^4] @RN4982 defined student market segments in ordinal terms -- local, in-state, regional, and national -- and found that student market segment was primarily a function of social class, particularly parental income and parental education. @RN4982 also conceived of colleges as an ordinal hierarchy. As in @RN4808, good matches are the key to realizing enrollment goals. In turn, @RN4982 argue that good matches are defined by homophily, the idea that actors who share common characteristics are likely to form connections with one another [@mcpherson2001birds; @RN4975]. @RN4982 conduct a network analysis whereby two colleges are defined as competitors if a large number of students submit SAT scores to both colleges, @RN4982 "draw\[ing\] a fundamental conclusion about the structure of college choice: collegiate competition occurs principally between like institutions" (p. 46). Subsequent analyses investigate the tuition price and the socioeconomic composition of institutions in competition with one another. The takeaway is that like-colleges compete for like-students as defined by social class, with private selective colleges competing directly for students, charging the highest prices, and enrolling students with the highest socioeconomic status (p. 72):

[^4]: Whereas @RN5015 analyze devices that classify individuals, the Market Segment Model harkens back to the earlier era of geodemography, in which market research classified places for merchants based on the attributes of people who lived there [@RN4880; @RN4957]

> Students describe themselves socially simply by telling us the colleges and universities in which they are interested. The layering of collegiate competition is primarily a socioeconomic layering. The hierarchical structure of collegiate competition largely reflects the stratified social and economic dimensions of the communities from which colleges draw their students. Competition among colleges, as admissions officers have told us for so long, is in fact, a matter of keeping company with one's peers.

## Research questions and expected results

Our overarching research question is, what is the relationship between college Board Geomarkets and high school recruiting visits of selective private colleges and public research universities? Because we lack the longitudinal data neccessary for causal assertions, we investigate whether cross-sectional 2017 recruiting visit patterns are consistent with theoretical expectations about the performativity of Geomarkes and the Market Segment Model.

We disaggregate the overarching research question into three concrete questions. First, to what extent are visit patterns consistent with recommendations from the Market Segment Model? For selective private -- and most public -- institutions in our sample, the Market Segment Model recommends focusing on affluent Geomarkets located in regions where many students are likely to consider a college like yours [@RN4982].

In the contemporary "market configuration" of U.S. higher education [@RN4517], the enrollment economy for selective private colleges and the majority of public research universities depends on enrolling students willing to pay high tuition prices. The Market Segment Model is an algorithm for identifying the location of desirable patrons. Drawing from @RN5072, the US postsecondary education system is highly ordinal and so are student market segments. According to @RN4982, selective private colleges primarily depend on students from the regional and national market segments. Further, regional and national students tend to come from affluent, college-educated households. Affluent households are not scattered randomly across the country, but rather clump together in particular geographic communities. Like UK "league tables" [@RN5005], Geomarkets are a means of commensurating geographically disparate localities in terms of the number of students from each market segment. Imagine that the University of Arkansas has substantial regional but not national student demand and wants to enroll more out-of-state students. The Market Segment Model points to the affluent "TX 23 -- Collin & Rockwall" (near Dallas) and the "TX 15 -- Northwest Houston & Conroe School District" Geomarkets, which contain large numbers of regional and national students, but not the poorer "TX 19 -- City of Dallas" or "TX 17 -- City of Houston (East)," which contain relatively few regional and national students.

We answer RQ1 using simple descriptive statistics. We predict most colleges in our sample will adhere to a regional or national (but not an in-state) recruiting strategy, depending on whether they have regional or national enrollment demand. We also predict that colleges will disproportionately visit high schools located in affluent Geomarkets.

RQ2 asks, to what extent do College Board Geomarkets (X) explain which high schools receive recruiting visits (Y)? Drawing from the performativity concept, we argue that Geomarkets explain college recruiting visits to high schools -- even after controlling for school- and neighborhood-level covariates thought to explain recruiting visits -- because Geomarkets have become embedded in the architecture that produces recruiting visits. We highlight two mechanisms.

First, as described above, Geomarkets and the Market Segment model were the basis for the popular EPS software. Similar to the Black-Scholes model being written into spreadhseets used by options traders [@RN5067], Geomarkets and the logic of the Market Segment Model were embedded within EPS software, which encouraged colleges to identify promising Geomarkets and then select high schools to visit within these Geomarkets. Quantification often reduces the decision-making authority of local actors [@RN5007]. The Market Segment Model sought to replicate the aggregate knowledge of local admissions officers. On background, EM professionals told us that EPS software enabled colleges to plan travel without relying on admissions officers having strong local knowledge of their territories. EPS software often recommended visiting the same sets of affluent, high-achieving high schools that were receiving visits from other colleges. We were told that savvier, quantitatively-adept admissions offices used EPS to visit schools that EPS recommended ignoring because there would be less competition for the good students who attended these high schools. <!--Once this knowledge was quantified and commodified onto a CD-ROM, the local expertise of admissions officers becomes less valuable. The EPS product increases the ability of a college admissions leader -- working with College Board staff or an EM consultant -- to plan recruiting efforts centrally. -->

Second, Geomarkets may explain recruiting visits because Geomarkets became an organizing principle for how admissions offices allocate admissions recruiters to territories. This process exemplifies performativity [@RN5067]; Geomarkets were created to mirror the territories of admissions officers [@RN4982] and, over time, admissions offices structured recruiting territories around Geomarkets. On background, admissions officers and EM consultants told us that Geomarkets became part of the shorthand lexicon of the National Association of College Admissions Officers (NACAC). For example, admissions officers introduce themselves to one another by saying something like, "I recruit 'PA 2'," which refers to the "Chester County, PA Geomarket." We find evidence for this claim scattered across the internet. For example, the LinkedIn profile of an admissions officer states, "Personally managed schools in Indiana geomarket's 1, 2, 3, 4, 5, 6, 7, & 9" \[CITE\]. A report from the Dartmouth College Admissions Ambassador Program lists the number of interviewers and applicants by Geomarket \[CITE\]. Although Geomarkets are utilized (agenced) by admissions professionals rather than prospective students, Admissions websites occassionally show concordance between Geomarkets and recruiting territories assigned to admissions officers. Examples include the Chicago-land recruiting territories of the University of Chicago \[CITE\], Lake Forest University, \[CITE\], and Saint Mary's College \[CITE\]. Anecdotal evidence suggests that admissions offices allocate relatively more admissions officers to affluent Geomarkets. For example, For example, the University of Chicago assigns one recruiter to the "IL 9 - North Shore" Geomarket, which had a 2020 population of about 161,000 and one recruiter to the "IL 12 - South and Southwest Suburbs" Geomarket, which had a 2020 population of about 1.2 million. <!--
files for all of these references can be found in here: /Users/jaquette/Documents/cb_geo/assets/images/evidence_of_geomarkets
-->

Additionally, we find evidence that higher education Customer Relationship Management (CRM) and Information System incorporate Geomarkets. Slate is the market-leading CRM for admissions and recruiting. Slate software allows colleges to assign admissions recruiters and prospective students to Geomarkets \[CITE\]. As another example, Oracle's PeopleSoft Campus Solutions student information system product integrates Geomarkets (referred to as "EPS Market Codes") and EPS. Oracle software documentation reads \[CITE\]:

> EPS is a geographic and demographic data service offered annually by the College Board to Colleges and Universities. EPS provides information to subscribing institutions about competitors, feeder schools, and demographic strengths and weaknesses. EPS market codes are proprietary market codes owned by the College Board and are used to categorize external organizations and people into geographical areas, mostly in the United States. Some admissions offices use EPS market codes to focus their recruiting efforts in geographic areas in which they believe they will be the most successful.

RQ3 asks, to what extent does Geomarket popularity -- measured as the number of visits per school -- mediate the relationship between school composition and the probability of a receiving a visit? Previous research shows that having a high proportion of free-reduced lunch or Black/Hispanic students is negatively associated with receiving a visit [@RN4758]. Therefore, RQ3 investigates whether high- versus low-SES schools (and low versus high share of Black/Hispanic enrollment) benefit more from being located in a popular Geomarket. We hypothesize that high-SES and low Black/Hispanic enrollment schools benefit more from being located in a popular Geomarket. Our rationale draws from @RN4808, who highlight the role of "good matches" between ordinally classified products and ordinally classified customers. @RN5072 [pp. 20-21] offers an anecdote:

> One of the authors had a credit card transaction denied while trying to refill her car’s gas tank in a high-poverty Oakland neighborhood. The clerk indicated with resigned anger that the location of his gas station was the likely cause of the problem. Back in Berkeley a few minutes later, the card worked without a hitch.

Not coincidentally, Oakland is in Geomarket "CA 7 -- City of Oakland" whereas Berkeley is in Geomarket "CA 8 -- Alameda County excluding Oakland." @RN4808 [p. 17] write that "‘good matches’ are perceived as natural because they fit well with how things already are." An affluent school in an affluent Geomarket is a good match because it exemplifies the schools we expect to find. We predict that such schools benefit by receiving more visits than an affluent school in a less affluent Geomarket. By contrast, a poor or predominantly Black/Hispanic school in an affluent Geomarket does not match expectations and will not reap the same locational benefits.

**Scholarly contribution**. Sociology of education is concerned with socioeconomic and racial inequality. Empirical scholarship primarily locates the source of inequality in the behavior of households, schools, colleges, and policies [see reviews by @RN4873; @RN2377]. However, scholarship has an underdeveloped understanding of inequality caused by third-parties that mediate between consumers and sellers. Scholars have investigated intermediaries that "occupy the interface between consumers and producers" [@RN5065, p. 1], including scholarship on college rankings [@RN5003] and school rankings [@RN5005; @RN5075; @hasankumar2019Digitization]. To our knowledge, intermediaries that classify consumers on behalf of sellers -- akin to classification situations [@RN4810] and including the field of market research -- have rarely been the object of empirical research [but see @RN5039]. Although consumer-facing intermediaries are highly salient to media outlets and researchers, intermediaries that classify consumers for businesses are more sophisticated and pervasive [@RN4957; @RN5064; @RN5073; @RN4808] and may be highly salient to professionals responsible for identifying and recruiting customers.

This manuscript speaks to the performativity consequences of market devices by examining how College Board Geomarkets and the Market Segment Model mediate recruiting visits made by colleges to high schools. In doing so, we make three contributions to the sociology of education. First, to our knowledge, this is the first empirical analysis based on concepts from the market devices literature. We argue that the market devices literature offers great utility for future research that investigates the growing role of third-party vendors in schools and colleges. Second, whereas existing scholarship assumes that enrollment management behavior is a function of individual colleges [e.g., @RN4758], we show how third-party market devices structure the recruiting behavior of individual colleges. Third, and most narrowly, we contribute to a critical sociology of the College Board. Existing research mirrors the blind-spot observed in scholarship on intermediaries by focusing on consumer-facing testing products \[CITE\]. This manuscript shows that College Board testing products are the basis for business-facing products that classify prospective students on behalf of colleges. Finally, analyses for RQ3 make a targeted contribution to the classification situations literature [@RN5015] by assessing idea of "good matches" between producers and consumers.

```{=html}
<!-- OG PARAGRAPHS
Scholarship about third-parties that mediate between consumers and producers/sellers considers two broad types of intermidiaries: intermediaries "that occupy the interface between consumers and producers" [@RN5065, p. 1], including college rankings and expert critics; and intermediaries akin to the "classification situations" of @RN4810 that classify consumers on behalf of sellers. We might cede that consumer-facing product ratings have more pathways of influence; they discipline consumer preferences, which in turn disciplines product attributes created by producers. On the other hand, intermediaries that classify consumers for the sake of producers -- including the entire field of market research -- are much more sophisticated [@RN4957; @RN5064; @RN5073; @RN4808]. To our knowledge, scholarship on quantification in the sociology of education has mostly focused on consumer-facing intermediaries. Certainly college rankings [@RN5003] and school rankings [@RN5005; @RN5075; @hasankumar2019Digitization] are salient for decision-makers and have important consequences. Perhaps another reason for the volume of scholarship about consumer-facing intermediaries is that coverage by the popular press makes them known to researchers. Intermediaries that classify consumers for businesses receive scant attention from the popular press but may highly salient for professionals who are responsible for identifying and recruiting customers. 

Robust literatures in the sociolology of organizations [@RN4421] and the sociology of education [@fast2025racializeddecoupling; @RN5055; @RN4873] shows how the behavior of organizations reproduces racial, class, and gender inequality \[CITE\]. @RN5070 contributes to scholarship on gender inequality because scholarship that locates inequality in organizational behavior fails to observe gender inequality produced by the market. @RN4873 casts colleges as sorting machines that incorporate and reproduce social inequality. This line of research fails to consider how the market devices utilized by colleges incorporate and reproduce social inequality. Whereas @RN5070 shows that market devices produce social inequality by directly classifying consumers, this manuscript investigates how market devices reproduce inequatlity of opportunity by disciplining how colleges classify consumers.

-->
```

# Discussion

```{=html}
<!-- 

> Admissions officers invariably are tellers of stories -- about the colleges they represent, about the colleges they attended, about each other, and about the often vagabond life of college recruiting\ldots We have begun with this celebration of storytelling\ldots \[because\] we believe that the intuitions of admissions officers actually comprise a remarkably systematic body of knowledge about the college selection process\ldots Our research is based upon listening carefully to what admissions officers have to say (pp. 9-10).

The Market Segment Model is the product of practioner-derived market research. In the 2000s, College Board created the *Segment Analysis Service* product [@RN4565] as an application of geodemographic market research logics -- associated with mail-order catalogs -- to the case of college choice [@RN4957]. By contrast, @RN4982 conceived of the Market Segment Model as an effort to "capture and quantify" (p. 11) the knowledge of admissions officers:
-->
```

# References

\singlespacing
\begingroup
\small

::: {#refs}
:::

```{=html}
<!-- TABLES 
\endgroup
\clearpage
\singlespacing
-->
```
